
<article>
	<div class="s12">
		<h1><?=t('Escritorio Virtual II')?></h1>
		<h2><?=t('Configuración')?></h2>
		<h3><?=t('Rol del jugador')?></h3>
		<p><?=t('Si vas dirigir una partida, eres el máster, de lo contrario, eres un jugador.')?></p>
	</div>

	<div class="s12 m6">
		<a role="button" href="/ev/ajustes/guardar/jugador_rol/jugador"><?=t('Soy un jugador')?></a>
	</div>

	<div class="s12 m6">
		<a role="button" class="outline" href="/ev/ajustes/guardar/jugador_rol/master"><?=t('Soy un máster')?></a>
	</div>
</article>
