
<div class="s6 m3">
	<a role="button" href="/ev/configuraciones"><?=t('Configuraciones')?></a>
</div>

<div class="clear"></div>

<article>
	<div class="s12">
		<h1><?=t('Escritorio Virtual II')?></h1>
		<h2><?=t('Configuración')?></h2>
		<h3><?=t('Partidas')?></h3>
		<p><?=t('¿Quieres crear una partida nueva o abrir una qué ya hayas creado?')?></p>
	</div>

	<div class="s12 m6">
		<a role="button" href="/ev/partidas/crear"><?=t('Crear partida')?></a>
	</div>

	<div class="s12 m6">
		<a role="button" href="/ev/partidas"><?=t('Elegir partida')?></a>
	</div>
</article>
