
<ol>
    <li>
        <p><?=t('<b>Velocidad:</b> Nuestra primera premisa es la experiencia de usuario y el primer factor para lograrlo es la velocidad; la plataforma ha de ser rápida como el demonio. Nada de esperar segundos cada vez que se refresca una página.')?></p>
    </li>
    <li>
        <p><?=t('<b>Aspecto visual:</b> El segundo factor para conseguir una excelente experiencia de usuario, es que el diseño entre por los ojos y esté cuidado al detalle para que todo encaje.')?></p>
    </li>
    <li>
        <p><?=t('<b>Menos es más:</b> Si algo no se utiliza o no funciona como se espera, lo quitamos y con ello mejoramos el mantenimiento del conjunto.')?></p>
    </li>
    <li>
        <p><?=t('<b>Principios KISS & DRY:</b> Si algo puede ser más sencillo, le damos las vueltas que haga falta para que así sea. Si podemos usar lo que tenemos, no añadimos cosas nuevas, lo adaptamos para ello.')?></p>
    </li>
</ol>
