
<ol class="pr10">
    <li><p><?=t('<b>Bienvenido</b> visitante. En estas líneas tengo el placer de expresarle una serie de buenas prácticas.')?><br>
    <?=t('En primer lugar indicarle que usted no está obligado a nada una vez registrado, puede permanecer de observador leyendo, usar las funciones disponibles y/o compartir con otros usuarios de esta red social, ideas, conocimiento y sabiduría entre otros, en formato texto y también multimedia.')?></p></li>

    <li><p><?=t('Sobre sus datos resgistrados (email y nombre de usuario) y el tratamiento que le damos a estos, se detalla en el enlace de Privacidad. En resumen, no hay política por encima de la establecida en la ley y lo detallado es aquello que esta nos dice.')?></p></li>

    <li><p><?=t('Respecto a las galletas o cookies, le diremos que no hacemos uso de galletas de terceros a conciencia, aunque sí hemos podido observar que el material multimedia embebido externo, trabaja al respecto con autonomía propia y ajeno a como nos gustaría. Por nuestra parte solo usamos una galleta propia, la que le permite acceder sin volver a pasar por el formulario de acceso. Dicho esto y si continúa navegando por este sitio, nos da a entender que acepta el uso de galletas según lo expuesto. De todas formas puede ponerse en contacto con nosotros desde el formulario de contacto y plantearnos cualquier tipo de duda sobre la red social, estaremos encantados de ayudarle con información precisa.')?></p></li>

    <li><p><?=t('A la hora de sumar contenido a esta red social, usted es totalmente responsable del texto y multimedia que comparte. Nuestro principio está basado en el respecto a los demás, por lo que está tajantemente prohibido expresar cualquier tipo de odio a otros, o incitar a ello por representar una minoría o simplemente una diferencia.')?><br>
    <?=t('Decirle también, que al compartir material, sobretodo multimedia, este debe ser y estar libre de derechos de autor.')?><br>
    <?=t('Si alguno de estos dos casos no se cumple, será amonestado y en el caso de reincidir, expulsado.')?></p></li>

    <li><p><?=t('Queda terminantemente prohibido la suplantación de identidad o el uso de varias cuentas. Esto último sólo será permitido si es pertinente y justificable.')?></p></li>

    <li><p><?=t('Los moderadores son seres humanos que tendrán que tomar decisiones en el momento sobre qué contenido merece ser eliminado en base a las circunstancias concretas, ya que no es posible crear normas que abarquen todas las situaciones.')?></p></li>

    <li><p><?=t('En todo momento, tendrá un formulario de contacto y otras vías para notificar abusos, sugerencias, reclamaciones o cualquier otra cosa que le preocupe. Escuchamos a todo el mundo y damos respuesta a todas las inquietudes.')?></p></li>

    <li><p><?=t('Por último queremos recordarle que la plataforma mantiene una actividad alta de desarrollo y por ello es posible encontrar alguna anomalía inesperada, pero sin duda pasajera. Estaremos a su disposición y muy agradecidos si nos hiciera llegar cualquier tipo de sugerencia o mejora. Valoramos todas las ideas, por pequeñas que sean y las tenemos en consideración.')?></p></li>
</ol>

<div class="pa10">
    <p><em><?=t('Espero que estas normas les sea de agrado, pues han mantenido hasta ahora nuestra red limpia y centrada en compartir nuestra afición. Gracias por su comprensión y bienvenido nuevamente.')?></em></p>
</div>
