
<div class="pl20">
    <p><?=t('Poner publicidad en R+ es así de fácil:')?></p>
</div>
<ol>
    <li><p><?=t('La publicidad se sitúa entre los bocadillos que se ven en la parte izquierda de la WEB. Observe los números situados arriba a la derecha de cada bocadillo. Estos números indican lo que se paga en euros al mes por cada bocadillo. Por lo tanto, debería observar donde quiere posicionarse, pues cuanto más pague, más arriba aparecerá su bocadillo con su anuncio.')?></p></li>

    <li><p><?=t('Ingrese vía PayPal a dj@roleplus.app la cantidad<sup>1</sup> deseada (sin céntimos) para un bocadillo de 250x250px. El doble para un bocadillo de 500x250px. El triple por un bocadillo de 750x250px. Así en adelante.')?></p></li>

    <li><p><?=t('Envíe a <a href="mailto:dj@roleplus.app?subject=Imagen y el enlace de mi bocadillo">dj@roleplus.app</a> la imagen y el enlace a su página de aterrizaje, donde pueda medir las estadísticas para este acceso exclusivo. Se admiten los formatos JPG o PNG, en ningún caso GIF.')?></p></li>

    <li><p><?=t('Su bocadillo tiene una duración de 30 días<sup>2</sup> tras haber pagado. Cada mes deberá repetir estos pasos por cada bocadillo con su anuncio que quiera renovar.')?></p></li>
</ol>
<hr>
<div class="pl20">
    <small>
        <p>1. <?=t('El precio incluye IVA e IRPF en el importe total de la factura.')?></p>
        <p>2. <?=t('En el caso de los mecenazgos, mantenemos el anuncio todo lo que dure la campaña, incluso los días previos por el precio del mes.')?></p>
    </small>
</div>
