
<section>
    <p><?=t('Esta mejora permite añadir una reacción a una publicación que nos ha hecho sentir algo y con ello transferir de 1 o 5 puntos de nuestra experiencia al creador de esa publicación.')?></p>
    <br>
    <p><?=t('Hay dos grupos de reacciones: uno con emoji de caras habituales y otro con emoji más exóticos. Los primeros entregan 1 PX y los otros 5 PX.')?></p>
</section>
<br>
<img alt="<?=t('Los dos grupos de reacciones')?>" src="/img/otras/reacciones.jpg" width="100%">
<br>
<section class="align-center">
    <?php View::partial('suscribirse', false, [
        'atributos'=>'data-bg_color',
        'id'=>'58HFSRCHHRWDN',
        'texto'=>t('Quiero donar €')
    ]); ?>
</section>
<br>
