
<ul>
    <li>
        <p><b><?=t('Carpetas:')?></b><br>
        1) <?=t('Puedes crear carpetas en tu perfil o en tus grupos, pulsando el candado para ver las opciones de edición. Busca el campo habilitado para crear carpetas, pon un nombre y al pulsar el botón será creada.')?><br>
        2) <?=t('Tus publicciones y las de otros las podrás incluir en tus carpetas, desde los 3 puntos verticales que ofrece cada publicación. Sí la publicción es tuya, la ubicación real cambiará y si son de otros, simplemente quedan enlazadas y las verás dentro de la carpeta escogida.<br>
        3) También puedes mover publicaciones de otros que publiquen en carpetas del grupo que administras.')?><br>
        4) <?=t('Para borrar una carpeta, guárdala dejando el nombre en blanco.')?>
    </li>
    <li>
        <p><b><?=t('Grupos:')?></b><br>
        1) <?=t('Puedes crear un grupo yendo a <a href="/grupos">https://roleplus.app/grupos</a> y pulsando en el icono de la hamburguesa junto al logo, cosa que abre el panel lateral izquierdo. En ese panel podrás escribir el nombre del grupo a crear, en el campo de texto habilitado para tal efecto.')?>
    </li>
    <li>
        <p><b><?=t('Publicaciones:')?></b><br>
        1) <?=t('Puedes formatear el texto de tus publicaciones usando las siguientes etiquetas')?>:<br>
        b, code, h3, h4, i, s, small, sub, sup, u<br>
        <?=t('Sintaxis')?>:<br>
        <?=t('1) Abrimos corchete')?>.<br>
        <?=t('2) Usamos una etiqueta permitida')?>.<br>
        <?=t('3) Cerramos corchete')?>.<br>
        <?=t('4) Incluimos el texto a formatear')?>.<br>
        <?=t('5) Abrimos corchete')?>.<br>
        <?=t('6) Incluimos la barra del siete')?> "/".<br>
        <?=t('7) Repetimos la etiqueta')?>.<br>
        <?=t('8) Cerramos corchete')?>.<br>
        <?=t('Ejemplo')?>:<br>
        [h3]<?=t('Soy un título')?>[/h3]
    </li>
    <li>
        <p><b><?=t('Usuarios:')?></b><br>
        1) <?=t('Puedes nombrar a un usuario en publicaciones y comentarios poniendo una arroba delante de su apodo y todo entre llaves, así: {@Mr demonio}')?>
    </li>
</ul>
