
<ol>
    <li><p><?=t('<b>Merchandise:</b> En un futuro haremos todo tipo de Merchandise que mole relacionado con la plataforma, Merchandise que querrás tener antes que los demás.')?></p></li>
    <li><p><?=t('<b>Publicidad:</b> La publicidad en R+ es una publicidad friki, llena de novedades, publicidad dirigida e interesante. Querrás estar al día de las cosas que van saliendo. Querrás enterarte de los ocasionales descuentos que se produzcan, etcétera.')?></p></li>
    <li><p><?=t('<b>Suscripciones:</b> Hay accesos a zonas exclusivas para miembros que paguen por ello una cuota mensual. Acceso a aplicaciones para jugar, el privilegio de quitar o poner publicidad, creación de zonas privadas, grupo donde podrás influir de primera mano en los desarrollos de la plataforma y todo ello según tu nivel de aportación.')?></p></li>
</ol>
<p><em></em></p>
