
<div class="pl20">
    <p><?=t('A continuación esbozamos todos los aspectos disponibles por niveles. Todo el mundo entra a la plataforma con nivel 1 y obtiene 1 PX por cada +1 atribuido a comentarios y publicaciones propias.')?></p>
</div>
<ol>
    <li>
        <p><?=t('<b>Espacio de disco exclusivo</b>, donde podrás guardar las fotos que uses en comentarios, publicaciones y perfiles de usuario y grupos.')?></p>
    </li>
    <li>
        <p><?=t('<b>Buscador y filtros de publicaciones, carpetas, etiquetas, grupos y usuarios</b>, donde podrás encontrar el contenido que necesites de forma rápida y precisa.')?></p>
    </li>
    <li>
        <p><?=t('<b>Puedes crear carpetas en tu perfil y grupos</b>, para organizar cada publicación.')?></p>
    </li>
    <li>
        <p><?=t('<b>Comentar publicaciones</b>, con múltiples vistas previas, vídeos de YouTube incrustados y fotos.')?></p>
    </li>
    <li>
        <p><?=t('<b>Modo oscuro</b>, para que ahorres energía y gastes menos el brillo de la pantalla. Tus ojos también lo agradecerán.')?></p>
    </li>
    <li>
        <p><?=t('<b>Crea grupos temáticos o basados en un juego</b>, donde la gente puede unirse a compartir sus ideas e inquietudes.')?></p>
    </li>
    <li>
        <p><?=t('<b>Notificaciones</b> cuando te siguen, comentan una de tus publicaciones, o comentan otra publicación donde ya has comentado o cuando te mencionan con {@Tu_apodo}.')?></p>
    </li>
    <li>
        <p><?=t('<b>Envía publicaciones a las carpetas de tu perfil o a las de un grupo</b> y aporta con ello noticias, artículos, enlaces, contenido útil, para que podamos todos enriquecernos de ello.')?></p>
    </li>
    <li>
        <p><?=t('<b>Encuentra usuarios, síguelos</b> o bloquéalos si te causan problemas. Tu eliges que publicaciones de que usuarios y grupos quieres ver en tu muro.')?></p>
    </li>
</ol>

<div class="mt15 pl20">
    <p><?=t('Los usuarios de nivel 2 (ver la tabla en configuración) acceden a los siguientes recursos:')?></p>
</div>
<ol>
    <li>
        <p><?=t('<b>Palanca para mostrar / ocultar el panel lateral izquierdo</b>, para dejar de ver la publicidad y ganar espacio de pantalla para otras cosas.')?></p>
    </li>
    <li>
        <p><?=t('<b>Una aplicación exclusiva para lanzar dados</b>. Aplicación que se desarrollará durante el mes de Diciembre y Enero de 2019 con los usuarios de nivel 4.')?></p>
    </li>
</ol>

<div class="mt15 pl20">
    <p><?=t('Los usuarios de nivel 3 acceden a los siguientes recursos:')?></p>
</div>
<ol>
    <li>
        <p><?=t('<b>Uso de APPs en beta hasta ser liberadas</b>. En este nivel estarás al día en cuanto a las APPs que estarán disponibles para los diferentes niveles.')?></p>
    </li>
    <li>
        <p><?=t('<b>Una aplicación para generar hojas de personaje</b>. Subes una imagen de fondo, crear campos y los posicionas en la hoja. Podrás imprimir la hoja o guardar los datos para usarlos online.')?></p>
    </li>
</ol>

<div class="mt15 pl20">
    <p><?=t('Los usuarios de nivel 4 acceden a los siguientes recursos:')?></p>
</div>
<ol>
    <li>
        <p><?=t('<b>Prioridad para influir</b>. Desde un grupo privado de Telegram, los usuarios de este nivel influyen en cada decisión tomada para el desarrollo de nuevos aspectos para la plataforma, así como de cada APP adjunta.')?></p>
    </li>
    <li>
        <p><?=t('<b>Una aplicación votada por la mayoría de los usuarios de este nivel</b>. El desarrollo de esta aplicación tiene que molar cacho. Habrá lluvia de ideas y le daremos forma a la idea resultante para llevarla acabo. A mi ahora mismo se me ocurre un ROLflix, donde se pueda ver en el momento los videos que sube un rolero en su canal de forma autónoma.')?></p>
    </li>
</ol>

<div class="mt15 pl20">
    <p><?=t('Los usuarios de nivel 4 acceden a los siguientes recursos:')?></p>
</div>
<ol>
    <li>
        <p><?=t('<b>Poder crear grupos privado</b>, para que un círculo de exclusivos amigos podáis crear material confidencial o que simplemente a otros les importa poco.')?></p>
    </li>
    <li>
        <p><?=t('<b>Otra aplicación o aspecto exclusivo</b>. Como nadie ha llegado a este nivel a día de hoy, nos daremos un tiempo para pensar que aplicación o aspecto se adapta mejor a las necesidades de un usuario de este nivel.')?></p>
    </li>
</ol>
