<?php $data_ajax = ($controller_name == 'usuarios' && $action_name == 'perfil') ? '' : ' data-ajax=".usuario._' . $usu->idu . ' footer"'; ?>

<a role="button" <?=empty($notificando[$usu->idu]) ? '' : 'class="outline"'?><?=$data_ajax?>
    rel="nofollow" href="/registrados/usuarios/notificar/<?=$usu->idu?>">
    <?=empty($notificando[$usu->idu]) ? t('Seguir') : t('No seguir')?>
</a>

<a role="button" <?=empty($bloqueados[$usu->idu]) ? '' : 'class="outline"'?><?=$data_ajax?>
    rel="nofollow" href="/registrados/usuarios/bloquear/<?=$usu->idu?>">
    <?=empty($bloqueados[$usu->idu]) ? t('Bloquear') : t('Desbloquear')?>
</a>

<a role="button" class="outline" data-ajax=".ajax.show" rel="nofollow" href="/registrados/conversaciones/crear/<?=$usu->idu?>"><?=t('Conversar')?></a>
