<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?=_view::partial('title')?></title>
        <link href="/css/aventuras.min.css?v=<?=$version?>" rel="stylesheet" type="text/css">
        <?=Css::inc()?>
    </head>
    <body>    
        <?=_view::$content?>
        <?=Js::inc()?>
    </body>
</html>
