<!DOCTYPE html>
<html data-color="<?= empty($claves['color']) ? 'red' : $claves['color'] ?>" data-theme="<?= empty($claves['tema']) ? 'light' : $claves['tema'] ?>" id="important" lang="es">
	<head>
		<meta charset="UTF-8">
		<meta content="public" http-equiv="Cache-control">
        <meta content="<?= t('Donde se publican las cosas.') ?>" name="description">
		<meta content="#ed8340" name="theme-color">
		<meta content="width=device-width, initial-scale=1" name="viewport">
		<title><?="$module_name $controller_name $action_name"?></title>

        <link href="/manifest.json?v=<?= $version ?>" rel="manifest">
        <link href="/css/ev.min.css?v=<?= $version ?>" rel="stylesheet">

		<?php if (empty($claves['quitar_masonry'])): ?>
		<link rel="stylesheet" href="/css/masonry.min.css?v=<?= $version ?>">
		<?php endif; ?>

		<?= Css::inc($version) ?>
	</head>
	<body>
        <div class="fondo"></div>

		<?php View::partial('ev/nav'); ?>

		<?php View::partial('ev/aside'); ?>

		<main>
			<?php View::content(); ?>
			<?php View::partial('toast'); ?>

			<div class="ajax show"></div>
		</main>

		<?php if (!Input::isAjax()): ?>
			<script src="/javascript/worker.js?v=<?= $version ?>" defer></script>
		<?php endif; ?>
		<script src="/javascript/ev.min.js?v=<?= $version ?>" data-idu="<?= Session::get('idu') ?>"></script>

		<?php if (empty($claves['quitar_masonry'])): ?>
		<script src="/javascript/masonry.min.js?v=<?= $version ?>"></script>
		<?php endif; ?>
		
		<?= Js::inc($version) ?>
	</body>
</html>