<?php
$confirmar_cierre = empty($confirmar_cierre) ? '' : 'data-confirm="' . t('¿Estás seguro?') . '"';
?>

<div class="modal <?=$width??''?>">
	<header>
        <h3><?=$titulo?></h3>
        
        <button class="transparent" <?=$confirmar_cierre?> data-hide=".modal, .overlay"><img alt="<?=t('Cerrar ventana')?>" src="/img/icons/x.svg"></button>
	</header>

    <?php if ( ! empty($filtro_filas)): ?>
        <section>
            <input type="text" class="w100" data-filter="<?=$filtro_filas?>" placeholder="<?=t('Filtrar')?>…">
        </section>
    <?php endif; ?>

    <?php View::content(); ?>
    <br>
    <br>
</div>
<div class="overlay" <?=$confirmar_cierre?> data-hide=".modal, .overlay"></div>
