<main sheet>

  <!-- 50% SUPERIOR: IMAGEN DE LA TABERNA -->
  <header>
    <img src="/img/aventuras/desapariciones/lugares/cazadores-en-la-taberna.png" alt="Interior de la taberna La Jarra Vacía">
  </header>

  <!-- SEGUNDA MITAD - 50% SUPERIOR: DESCRIPCIÓN E INTERACCIÓN -->
  <section>
    <h1>Cazadores en la taberna</h1>
    <p>Se accede al concluir los altercados de la plaza o al caer el crepúsculo sobre el pueblo.</p>
    <p><i>La taberna «La Jarra Vacía» es un antro de techo bajo y vigas ennegrecidas por el hollín, donde el aire es denso por el humo de pipas baratas y el olor a sudor rancio. El suelo está cubierto de serrín húmedo que oculta las manchas de cerveza, y los pocos clientes en los rincones susurran con miradas sospechosas hacia la entrada. Su antigua alegría ha sido reemplazada por un silencio tenso. Tras la barra, el tabernero Johann Linstine —un hombre con hombros caídos, arrugas de preocupación y manos temblorosas por falta de sueño— limpia las copas con un trapo mugriento, evitando mirar directamente a los ojos de los desconocidos.</i></p>
    <p>Invita a los PJ a describir sus acciones y buscar mesa. Pueden pedir consumiciones a Johann o sentarse cerca de los cazadores. Johann se mostrará Cauteloso de inicio y oculta que conspira junto a la herrera Jandice.</p>
  </section>

  <!-- SEGUNDA MITAD - 50% INFERIOR: INFORMACIÓN OCULTA QUE REQUIERE TIRADA -->
  <section>
    <p><b>(Con Escuchar o Cotilleo a Normal +/-0% o interactuando con los cazadores)</b></p>
    <p><i>Los cazadores en la mesa del rincón conversan sobre una banda de rebeldes en las colinas y una manada de lobos hambrientos en una cueva a ocho kilómetros. Uno de ellos fanfarronea con un mapa arrugado en la mano.</i></p>
    <p><i>Johann Linstine se acerca con la voz baja e inquieta y los ojos en la entrada: «Os ofrezco dos chelines de plata por cada lobo adulto muerto y diez peniques de bronce por cada cría. Hacen el camino intransitable y se han cobrado vidas. ¿Estaríais dispuestos a librarnos de esas bestias?».</i></p>
    <p>Una prueba de Carisma o Persuasión convence a los cazadores de revelar la ubicación de la cueva. Si deciden darles caza, Johann les entregará el mapa y formalizará la recompensa.</p>
  </section>

</main>
