<main sheet>

  <!-- 50% SUPERIOR: IMAGEN DE LA HERRERÍA -->
  <header>
    <img src="/img/aventuras/desapariciones/lugares/encargo-en-la-herreria.png" alt="La herrería de Jandice Kemptoff en la noche">
  </header>

  <!-- SEGUNDA MITAD - 50% SUPERIOR: DESCRIPCIÓN E INTERACCIÓN -->
  <section>
    <h1>La Herrería</h1>
    <p>Se desencadena al entrar los Personajes en la herrería y entablar conversación con Jandice.</p>
    <p><i>La herrería de Mullensburg es un edificio de piedra robusta y vigas de roble tiznadas, dominado por el horno de la forja que ahora yace con las brasas apenas templadas. El constante golpeteo del yunque ha cesado, sustituido por el siseo del viento y el olor a hierro frío, carbón apagado y grasa. En las paredes cuelgan herramientas desgastadas y moldes de herraduras llenos de polvo, reflejando la paralización debido al acaparamiento de metal de la fortaleza. La herrera, Jandice Kemptoff —una mujer robusta y de brazos fibrosos cubiertos de hollín, con delantal de cuero sobre ropas desgastadas y que sostiene un martillo de forja— limpia una de las mesas suspirando de frustración, mirándoos con sospecha y desesperación contenida.</i></p>
    <p>Jandice se muestra cansada y reacia a hablar al principio. Espera ver si muestran simpatía por el pueblo o desconfianza por la guardia. Oculta que conspira junto a Johann Linstine.</p>
  </section>

  <!-- SEGUNDA MITAD - 50% INFERIOR: EL ENCARGO Y LA INFORMACIÓN OCULTA -->
  <section>
    <p><b>(Con Negociar a Normal +/-0% para aumentar la recompensa)</b></p>
    <p><i>Jandice se asegura de que no hay oídos indiscretos, cierra a medias el portón de la forja y os susurra: «Una caravana familiar con materiales de gran valor ha desaparecido en el camino del duque. Os doy una corona de oro por investigar la zona, y otra más si regresáis con la mercancía intacta. ¿Estáis dispuestos a traerme de vuelta lo que es mío?».</i></p>
    <p>Si aceptan el trato, Jandice les dará detalles sobre la ruta. Una prueba exitosa de Negociar permite asegurar un pago por adelantado de 5 chelines de plata para provisiones.</p>
  </section>

</main>
