<main sheet>

  <!-- 50% SUPERIOR: IMAGEN DEL LUGAR -->
  <header>
    <img src="/img/aventuras/desapariciones/lugares/mullensburg.png" alt="El Valle de Mullensburg y la Frontera">
  </header>

  <!-- 25% INTERMEDIO: INFORMACIÓN CONOCIDA -->
  <section>
    <p><i>Nos encontramos en el siglo XVI. Mientras en las lejanas y ricas capitales el Renacimiento ilumina las mentes con arte y ciencia, aquí en la frontera solo ha traído formas más eficientes de matar. El oprimido pueblo de Mullensburg se halla junto a un afluente del río Ronthan, en la sangrienta linde entre el Reino de Barrenburg y el Ducado de Lapsburg. Lleváis tres años de una guerra devastadora que está asolando estas tierras. Lapsburg está perdiendo. El buen duque Frederick cayó en la primera campaña, dejando a un niño como heredero y al cruel Barón Von Aspinfeld gobernando con mano de hierro desde su Ciudadela de obsidiana. El invierno toca a su fin, el hambre aprieta y cualquier chispa de esperanza parece haber sido sepultada bajo el fango y la muerte.</i></p>
    <p>Campaña: DESAPARICIONES EN MULLENSBURG | Aventura: CONCORDANCIA DE LIBERTAD I. Lee este texto al inicio de la sesión para asentar el tono "Grim & Perilous". Deja claro a los jugadores que sus personajes están exhaustos, hambrientos y hartos de una guerra que no es suya, rodeados de miseria.</p>
  </section>

  <!-- 25% INFERIOR: INFORMACIÓN POR REVELAR -->
  <section>
    <p><b>(Con Educación, Folclore o Historia a Arduo -30%)</b></p>
    <p><i>Al indagar en las crónicas fronterizas y las viejas tensiones de la linde, recordáis que Mullensburg es mucho más que un montón de chozas embarradas bajo el yugo del Barón. Este asentamiento estratégico es el verdadero termómetro de la contienda: si la Ciudadela cae o el descontento popular estalla en las calles, todo el flanco occidental del Ducado de Lapsburg quedará completamente expuesto al avance implacable del Reino de Barrenburg, transformando este rincón olvidado en el detonante de una revolución inminente.</i></p>
    <p>Utiliza esta información histórica para justificar la importancia política del lugar y la urgencia de las misiones secundarias. Solo los eruditos o personajes vinculados a la estrategia militar comprenderán que lo que ocurre en este pueblo miserable afectará el destino de ambas naciones.</p>
  </section>

</main>