<main sheet>

  <!-- 50% SUPERIOR: IMAGEN DEL LUGAR -->
  <header>
    <img src="/img/aventuras/desapariciones/lugares/plaza.png" alt="Plaza central de Mullensburg al mediodía">
  </header>

  <!-- 25% INTERMEDIO: INFORMACIÓN CONOCIDA -->
  <section>
    <p><i>Alcanzáis la plaza de Mullensburg justo cuando el sol alcanza su cénit, aunque su luz apenas logra disipar la bruma de miseria que asfixia el lugar. El fango tiñe las calles y el ambiente rezuma una pesada apatía. Una veintena de campesinos de rostros demacrados y ropas raídas se agrupan en tensos corrillos, hundiendo las botas en el barro. Susurran entre dientes, recelosos, clavando en vosotros miradas furtivas mientras aguardan con palpable desesperación alguna noticia de los cazadores.</i></p>
    <p>Este es el momento idóneo para que los jugadores describan a sus personajes y establezcan sus interacciones iniciales. Los campesinos se muestran esquivos, pero están dispuestos a compartir sus quejas si se les tira un poco de la lengua y no ven guardias cerca.</p>
  </section>

  <!-- 25% INFERIOR: INFORMACIÓN POR REVELAR -->
  <section>
    <p><b>(Con Escuchar o Cotilleo a Fácil +20%)</b></p>
    <ul>
      <li><i>«El Barón Von Aspinfeld no ha salido de sus aposentos en la Ciudadela durante las últimas dos semanas; algo oscuro ocurre allí arriba».</i></li>
      <li><i>«Las puertas del templo del vicario Gregor vuelven a estar cerradas a cal y canto, y por las noches se filtran ruidos espantosos. Seguro que el muy bastardo vuelve a estar ebrio».</i></li>
      <li><i>«Los lobos han regresado a las colinas; sus aullidos suenan más furiosos y hambrientos que nunca».</i></li>
      <li><i>«El trágico incendio que calcinó la casa de los Alkerdof no fue un accidente, sino pura voluntad de los dioses... o algo peor».</i></li>
      <li><i>«Johann, el posadero, se reúne a escondidas con forasteros envueltos en sombras en plena noche».</i></li>
    </ul>
    <p>Cada éxito en la tirada permite a un personaje obtener uno o dos de estos rumores de forma orgánica durante la conversación con los lugareños. Si hay una pifia, alguien podría alertar a los hombres del Barón prematuramente sobre la presencia de extraños entrometidos.</p>
  </section>

</main>