
<article>
	<header>
		<h1>5) <?=t('¿Hay creada una escena?')?></h1>
		<h2><?=t('Las escenas agrupan la multimedia de la aventura.')?></h2>
	</header>

	<section>
		<h3><?=t('Si NO lo está toca crearla:')?></h3>
		<div class="grid">
			<a class="outline" role="button" href="/ev/escenas/aventura/<?=$aventuras_idu?>"><?=t('Ver escenas')?></a>
			<a role="button" href="/ev/escenas/formulario/<?=$aventuras_idu?>"><?=t('Crear escena')?></a>
		</div>
	</section>
	<br>
	<footer>
		<form action="/ev/asistente/elementos" method="post">
			<h3><?=t('Si está creada toca escoger una y darle a siguiente:')?></h3>
			<select name="escenas_idu">
				<option value=""><?=t('Escoger una...')?></option>
				<?php foreach ($escenas as $esc):
					$selected = ($escenas_idu == $esc->idu) ? 'selected' : ''; ?>
					<option <?=$selected?> value="<?=$esc->idu?>"><?=$esc->nombre?></option>
				<?php endforeach; ?>
			</select>
			<div class="grid">
				<a class="outline" role="button" href="/ev/asistente/aventuras"><?=t('Anterior')?></a>
				<button type="submit"><?=t('Siguiente')?></button>
			</div>
		</form>
	</footer>
</article>
