
<article>
	<div class="s12">
		<h1><?=_('Escritorio Virtual II')?></h1>
		<h2><?=_('Configuración')?></h2>
		<h3><?=_('Rol del jugador')?></h3>
		<p><?=_('Si vas dirigir una partida, eres el máster, de lo contrario, eres un jugador.')?></p>
	</div>

	<div class="s12 m6">
		<a role="button" href="/ev/ajustes/guardar/jugador_rol/jugador"><?=_('Soy un jugador')?></a>
	</div>

	<div class="s12 m6">
		<a role="button" href="/ev/ajustes/guardar/jugador_rol/master"><?=_('Soy un máster')?></a>
	</div>
</article>
