<aside class="editor index hide pa10">
	<button data-hide="aside">
		<?=t('Contraer')?>
		<?=Ku::icon('arrow-right')?>
	</button>		

	<ul id="menu-reglas-sortable">
		<?php foreach($reglas as $reg): 
			$hash = '';
			if (preg_match('/<article\b[^>]*\bid=["\']([^"\']+)["\']/i', $reg->descripcion, $matches)) {
				$hash = $matches[1];
			}
			if ($hash === '') {
				$hash = _url::slug($reg->nombre);
			}
		?>
			<li data-idu="<?=$reg->idu?>"><a href="#<?=$hash?>"><?=$reg->nombre?> <sup class="nowrap regla-peso"><?=$reg->peso?></sup></a></li>
		<?php endforeach; ?>
	</ul>
</aside>
