
<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>

<div class="brick card">
	<img src="https://source.unsplash.com/collection/<?=rand(1, 999999)?>" alt="Card example image">
	<div class="card-body">
		<h4 class="card-title">My awesome Paper card!</h4>
		<h5 class="card-subtitle">Nice looking subtitle.</h5>
		<p class="card-text">Notice that the card width in this example have been set to 20rem, otherwise it will try to fill the current container/row where the card is.</p>
		<div class="row flex-spaces">
			<button>Read More</button>
			<button>5 Comments</button>
		</div>
	</div>
</div>
