<fieldset>
    <legend>Carpetas huerfanas en /img/usuarios/</legend>
    <header>
        <a role="button" href="/atalaya/archivos/borrar_carpetas_de_imagenes_huerfanas/borrar">Borrar carpetas huerfanas</a>

        <a role="button" href="/atalaya/archivos/borrar_carpetas_de_imagenes_huerfanas">Recargar</a>
    </header>
    <section>
        <pre><?php _var::echo($carpetas); ?></pre>
    </section>
</fieldset>