<fieldset>
    <legend>Carpetas huerfanas en /img/vistas_previas/</legend>
    <header>
        <a role="button" href="/atalaya/archivos/borrar_imagenes_huerfanas_en_vistas_previas/borrar">Borrar imágenes huérfanas en vistas previas</a>

        <a role="button" href="/atalaya/archivos/borrar_imagenes_huerfanas_en_vistas_previas">Recargar</a>
    </header>
    <section>
        <pre><?php _var::echo($carpetas); ?></pre>
    </section>
</fieldset>