
<div data-columns id="grid">
    <article>
        <header>
            <h1><?=t('Estado y funcionalidades de R+')?></h1>
        </header>

        <section>
            <h2><?=t('Leyenda')?></h2>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Estable/Hecho.')?>
                </li>
                <li>
                    <span class="point yellow"></span> <?=t('Actualizando/Pendiente.')?>
                </li>
                <li>
                    <span class="point orange"></span> <?=t('Inestable/Revisando.')?>
                </li>
                <li>
                    <span class="point red"></span> <?=t('Avería/Revisando.')?>
                </li>
                <li>
                    <span class="point grey"></span> <?=t('Desatendida/Parado.')?>
                </li>
            </ul>
        </section>

        <footer></footer>
    </article>

    <article>
        <header>
            <h2><?=t('R+1 nace con el cierre de G+')?></h2>
            <p><small><b><?=t('Nombre en clave')?>:</b> Bralin</small></p>
        </header>

        <section>
            <?=t('Nació el 10 de octubre de 2018 y estuvo con nosotros aproximadamente 2 años.')?><br>
        </section>

        <footer></footer>
    </article>

    <article>
        <header>
            <h2><?=t('R+1.5 para las VirtuaLES')?></h2>
            <p><small><b><?=t('Nombre en clave')?>:</b> LES</small></p>
        </header>

        <section>
            <?=t('Las LES nos pidió que optimizásemos la velocidad de la red en general, que dejásemos el formulario de acceso solo para las zonas de escritura en base de datos y que su perfil de usuario fuera una cartelera para los participantes y así se hizo. R+ se adaptó a estas jornadas virtuales tan emblemáticas y se desarrollaron durante 3 días con más de 40 usuarios simultáneos. Nuestro record al respecto.')?><br>
        </section>

        <footer></footer>
    </article>

    <article>
        <header>
            <h2>R+2</h2>
            <p><small><b><?=t('Nombre en clave')?>:</b> MrsDeath</small></p>
        </header>

        <section>
            <h3><?=t('Aspecto general')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Avatares y textos más grandes.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Barra de navegación simplificada.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Menú lateral izquierdo por roles.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Filtro caliente o búsqueda pulsando enter.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Optimizado para soportar más usuarios.')?><br>
                </li>
            </ul>

            <h3><?=t('Ajustes')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Configuración por roles.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Control de suscripciones PUSH y de cache.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Modo de día y de noche.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Palanca para desactivar el Masonry.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Palanca para desactivar la publicidad.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Palanca para desactivar las notificaciones +1.')?>
                </li>
                <li>
                    <span class="point yellow"></span> <?=t('Transferir PX de chamán a otro rol.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('18 colores primarios para elegir.')?>
                </li>
            </ul>

            <h3><?=t('Publicaciones')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Aviso/Contador de publicaciones nuevas.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Crear publicaciones normales.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Crear publicaciones de tipo evento.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Crear publicaciones con encueta.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editar publicaciones.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Borrar publicaciones.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Fotos múltiples para ver en horizontal.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Vistas previas.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Campana para ser notificado en publicaciones ajenas.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Icono de ver publicación cuando no hay título.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Enlaces y títulos se acortan a una línea.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('El título y algo de texto es obligatorio.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('+1 y +5 (Me encanta) en publicaciones.')?>
                </li>
            </ul>

            <h3><?=t('Perfiles siguiendo')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Listado solo con las publicaciones de usuarios que sigues.')?>
                </li>
            </ul>

            <h3><?=t('Comentarios')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Crear comentarios.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Borrar comentarios.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editar comentarios.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Fotos múltiples para ver en horizontal.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Vistas previas.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('+1 en comentarios.')?>
                </li>
            </ul>

            <h3><?=t('Comentarios sueltos')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Listado de los comentarios de las publicaciones.')?>
                </li>
            </ul>

            <h3><?=t('Usuarios')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Formulario de acceso.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Listado con opción de seguimiento.')?>
                </li>
            </ul>

            <h3><?=t('Grupos')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Crear grupo')?>.
                </li>
                <li>
                    <span class="point green"></span> <?=t('Borrar grupo.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editar grupo.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Listado de grupos.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Publicación etiquetada.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Unirse al grupo.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Dejar grupo.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Subir un mapa al grupo.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Acercar/Alejar el mapa.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Crear chincheta en mapa.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editar chincheta en mapa.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Quitar chincheta en mapa.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Mostrar/Ocultar chinchetas.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Buscar info en chinchetas.')?>
                </li>
                <li>
                    <span class="point yellow"></span> <?=t('Crear conversación de grupo.')?>
                </li>
            </ul>

            <h3>RSS</h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Lector de entradas de blogs.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Lector de entradas de canales de YouTube.')?>
                </li>
                <li>
                    <span class="point green"></span> ROLEFLIX.
                </li>
            </ul>

            <h3><?=t('Consejos autogestionados')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Crear consejo')?>.
                </li>
                <li>
                    <span class="point green"></span> <?=t('Duplicar consejo')?>.
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editar consejo')?>.
                </li>
                <li>
                    <span class="point green"></span> <?=t('Eliminar consejo')?>.
                </li>
            </ul>

            <h3><?=t('Tienda de apoyo a la plataforma')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Adquirir PX')?>.
                </li>
                <li>
                    <span class="point yellow"></span> <?=t('Automatizado para poner publicidad.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Compra de roles y suscripción a chamán.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Invitar a café por PayPal o Kofi.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Recompensas por códigos')?>.
                </li>
                <li>
                    <span class="point green"></span> <?=t('Tienda externa de regalos y camisetas.')?>
                </li>
            </ul>

            <h3><?=t('Escritorio Virtual II')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Asistente para no perderse.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Chat con dados.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editor de aventuras compartidas.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editor de fichas para aventuras.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editor de manuales de rol.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editor de post-it con texto, imagen, audio, vídeo.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Editor de partidas (aventura+jugadores).')?>
                </li>
                <li>
                    <span class="point yellow"></span> <?=t('Panel genérico para emitir.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Panel para el jugador.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Panel para el máster.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Pestaña para ver el fondo sin post-it.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Pestaña para videollamada con Jitsi.')?>
                </li>
            </ul>

            <h3><?=t('Notificaciones')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Aviso/Contador de notificaciones nuevas.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Marcar todas como leídas.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Marcar una como leída.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('No se notifica a los usuarios con un bloqueo activo.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Notificación a seguidores de un usuario cuando este publica.')?>
                </li>
                <li>
                    <span class="point green"></span>
                    <?=t('Notificación a seguidores de un grupo cuando alguien publica con la etiqueta de este.')?>
                </li>
                <li>
                    <span class="point green"></span>
                    <?=t('Notificación al usuario de un perfil cuando otro empieza a seguirle.')?>
                </li>
                <li>
                    <span class="point green"></span>
                    <?=t('Notificación cuando alguien comenta una publicación creada o siguiendo.')?>
                </li>
                <li>
                    <span class="point yellow"></span>
                    <?=t('Notificación cuando alguien envía un mensaje de conversación.')?>
                </li>
                <li>
                    <span class="point green"></span>
                    <?=t('Notificación cuando alguien es mencionado en publicacion o comentario.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Notificación cuando se recibe un me gusta en un comentario.')?>
                </li>
                <li>
                    <span class="point green"></span>
                    <?=t('Notificación cuando se recibe un me gusta o me encanta en una publicación.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Ventana donde ver nuevas y viejas notificaciones.')?>
                </li>
            </ul>
            
            <h3><?=t('Traducciones')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Buscador de lo traducido.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Enviar propuesta con comentario.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Listado de propuestas por su estado.')?>
                </li>
            </ul>

            <h3><?=t('Tareas')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Crear propuesta de tarea con comentario.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Listado de tareas según su estado.')?>
                </li>
            </ul>

            <h3><?=t('Estadísticas')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Top 10 de usuarios con más publicaciones.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Top 10 de usuarios con más comentarios.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Gráfica con el nº de publicaciones por meses.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Gráfica con el nº de comentarios por meses.')?>
                </li>
            </ul>

            <h3><?=t('Créditos')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Listado de patrones.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Listado de colaboradores.')?>
                </li>
            </ul>

            <h3><?=t('Servidores nuevos')?></h3>
            <ul>
                <li>
                    <span class="point green"></span> <?=t('Servidor principal.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Servidor de apoyo.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Servicio de BD.')?>
                </li>
                <li>
                    <span class="point green"></span> <?=t('Servicio de correo.')?>
                </li>
            </ul>
            <br>
            <h4><?=t('¿Qué hemos ganamos con los nuevos servidores?')?></h4>
            <p><?=t('Pasamos de tener 3 servidores y 1 ampliación de disco de 50 GB a 2 servidores con más del doble de prestaciones por el mismo precio.')?></p>

            <p><?=t('Pasamos a tener servidores con 1 core, 2 GB de memoria y 25 GB de disco SSD a servidores con 2 cores, 4 GB de memoria y 80 GB de disco SSD NVMe (5 veces más rápidos que los SSD normales).')?></p>
        </section>

        <footer></footer>
    </article>

    <article>
        <header>
            <h2><?=t('Hoja de ruta 2021 y 2022')?></h2>   
        </header>

        <section>
            <?=t('Enero de 2021:')?><br>
            — <?=t('Migramos R+2 con el EV2 a servidores nuevos.')?><br>
            <hr>
            <?=t('De febrero a junio:')?><br>
            — <?=t('Cambiamos el EV2 de escenas a lugares.')?><br>
            <hr>
            <?=t('Julio y agosto:')?><br>
            — <?=t('Reactivamos el chat.')?><br>
            <hr>
            <?=t('Septiembre:')?><br>
            — <?=t('Reactivamos los grupos con mapa interactivo.')?><br>
            <hr>
            <?=t('Octubre y noviembre:')?><br>
            —
            <?=t('Añadimos un gestor de tareas, un listado de comentarios y reactivamos la creación de manuales en el EV2.')?><br>
            <hr>
            <?=t('Diciembre:')?><br>
            — <?=t('Pondremos R+2 en 8 idiomas entre otras cosas.')?><br>
            <hr>
            <?=t('De enero a marzo de 2022:')?><br>
            — <?=t('Promovemos R+2 en Twitter.')?><br>
            <hr>
            <?=t('Diciembre 2022:')?><br>
            — <?=t('Lanzamos la beta de R+3')?><br>
        </section>

        <footer></footer>
    </article>
</div>
