<div class="clear"></div>
<footer>
    <div class="center">
        <a role="button" href="/estado">
            <?=Ku::img(t('Estado de R+'), '/img/icons/info.svg', 30, 30)?>    
        </a>

        <a role="button" href="/info/ventana/politicas" data-ajax=".ajax.show"><?=t('Políticas')?></a>

        <a role="button" href="/info/ventana/privacidad" data-ajax=".ajax.show"><?=t('Privacidad')?></a>
        
        <button type="button" class="scroll-top">
            <?=Ku::img(t('Volver arriba'), '/img/icons/arrow-up.svg', 30, 30)?>
        </button>
    </div>
</footer>
