
<div class="landing-page">
    <h1>Elige un plan para tu sueño</h1>
    <p>¿Cuál se adapta mejor a tus necesidades?</p>

    <img src="/img/consejos/TQ_Ilustracion-01.jpg" style="max-width:100%">

    <hr>
    <div class="plan-section">
        <h2>Plan 10: Banner por 10€ al mes</h2>
        <p>Envíanos tu banner a <span class="email-anti-spam">dj at roleplus dot app</span> con un tamaño de 640x640(x72)px y lo publicaremos en R+ mes a mes. Lo puedes cambiar en cualquier momento.</p>
        <div class="plan-10"></div>
    </div>
    <hr>
    <div class="plan-section">
        <h2>Plan 20: Banner y Diseño por 20€ al mes</h2>
        <p>Nosotros crearemos tu banner en 640x640(x72)px con el material gráfico que nos proporciones y lo publicaremos en R+ cada mes.</p>
        <div class="plan-20"></div>
    </div>
    <hr>
    <div class="plan-section">
        <h2>Plan 40: Servicio integral por 40€ al mes</h2>
        <p>Nos encargaremos de crear y modificar tu banner, cómo en el plan anterior, de acuerdo con tus promociones actuales. Además, publicaremos tu banner en R+ cada mes. ¡Y eso no es todo! Una vez por semana, publicaremos tu banner en todas nuestras redes: Twitter, Facebook e Instagram.</p>
        <div class="plan-40"></div>
    </div>
    <hr>
    <div class="testimonials">
        <h2>Testimonios</h2>

        <p><small><b>Andrés (greatkithain):</b><br>
        <i>Tras la diaspora de Google Plus como red social o comunidad rolera surgieron varias alternativas como redes sociales. R+ es una propuesta personal de Raúl a diferencia de las proporcionadas por las empresas propietarias de las redes sociales y aunque no participo activamente, me gusta apoyar la iniciativa y considero qué es lo más parecido a una comunidad proporcionando contenido, moderación, fichas y un lugar tranquilo para debatir y conocer cosas nuevas de nuestro hobby.</i></small></p>

        <p><small><b>Ángel Luis Pérez Velasco (Werty):</b><br>
        <i>Soy rolero desde niño. Así que si surge una red social sobre rol en mi idioma, definitivamente debo formar parte.</i></small></p>

        <p><small><b>Carlos Ferrer, autor del juego de rol Tierras Quebradas:</b><br>
        <i>Estoy en R+ porque me permite echar una ojeada a artículos y novedades interesantes sobre juegos de rol, y también porque tengo la posibilidad de informar sobre mis propios proyectos.</i></small></p>

        <p><small><b>EbaN:</b><br>
        <i>Yo estoy en R+ casi desde que empezó. Cuando cerró la red social de Google (G+) se habló de una red social de roleros para roleros, autogestionada para no depender de terceros. Y desde entonces aquí estoy.</i></small></p>

        <p><small><b>Faifolk:</b><br>
        <i>Por apoyar los proyectos roleros españoles.</i></small></p>

        <p><small><b>Goikorol:</b><br>
        <i>Yo no uso Facebook así que para mí es mi única fuente de información rolera, rápida y fácil, dónde puedo publicar a gusto mis actualizaciones.</i></small></p>

        <p><small><b>Mario C Thorkrim:</b><br>
        <i>Estoy en esta plataforma por la información que encuentro, más cercana a mis gustos, y para mantener contacto con personas con las que comparto ésos gustos. También para comentar alguna idea o noticias del mundillo de vez en cuando con un grupo de personas que no tengo bien localizadas o agrupadas en otras plataformas.</i></small></p>

        <p><small><b>Pablets De Avendanus:</b><br>
        <i>Ser rolero hispanohablante y no apoyar la existencia de una red social para el mundo rolero hispano, simplemente no tiene perdón de Sigmar.</i></small></p>

        <p><small><b>Xalabin:</b><br>
        <i>Para mí es un sitio donde informarme sobre temas roleros, tratar con los habituales y en el que tener alguna conversación interesante de tanto en tanto.</i></small></p>
    </div>
</div>
