
<div class="comunicaciones s12" data-columns id="grid">
    <article>
        <header>
            <h1 class="flex middle gap5"><?=Ku::icon('alert-circle')?> <?=t('Info')?></h1>
            <?=t('Le hemos dado de baja de nuestro boletín semanal y de futuras comunicaciones pasivas.')?><br>
            <i class="flex middle gap5"><small><?=Ku::icon('corner-down-right')?></small> <?=t('Puede reactivar el servicio en ajustes.')?></i>
        </header>
        <section>
            <hr>
            <b class="flex middle gap5"><?=Ku::icon('alert-octagon')?> <?=t('No tiene que hacer más.')?></b>
            <hr>
        </section>
        <footer>
            <i class="flex middle gap5"><?=Ku::icon('mail')?> <?=t('Si desea alguna otra cosa, escríbanos al correo')?>:</i>
            <a href="mailto:Dirección <dj@roleplus.app>">dj@roleplus.app</a>
        </footer>
    </article>
</div>

