
<article class="mha w600 formularios tabs">
	<header>
		<a href="/usuarios/identificarse" class="tab"><?=t("Identifícate")?></a>
		<a href="/usuarios/registrarse" class="tab active"><?=t("Regístrate")?></a>
		<a href="/usuarios/recordar_clave" class="tab"><?=t("Recuérdame")?></a>
	</header>
	
	<?=Form::open(null, 'post', 'class="container registrarse"')?> 
		<section>
			<br>&nbsp;
			<div class="align-center">
				<?php View::partial('google_login', null, ['button'=>'signup', 'url'=>'usuarios/registrarse_con_google']); ?>
			</div>
			<div class="align-center mv10">--- O ---</div>
			<?=Kubox::input(type: 'text',
				attrs: 'required tabindex="1"',
				label: t('Con un eMail que no sea el personal'),
				placeholder: t('Aquí el correo electrónico'),
				name: 'email', value: _var::post('email'))?>
			
			<br>
			<div class="bottom gap0">
				<?=Kubox::input(type: 'password',
					attrs: 'class="connect-to-right" required tabindex="2"',
					box: 'class="grow"',
					label: t('Una clave con un mínimo de 12 caracteres'),
					placeholder: t('Aquí la contraseña'),
					name: 'clave', value: _var::post('clave'))?>

				<button type="submit" class="connect-to-left" data-show_pass=".container.registrarse [name='clave']"><?=Ku::icon(t('Mostrar contraseña'), 'eye-s', 20, 20)?>
			</div>

			<br>
			<?=Kubox::input(type: 'text',
				attrs: 'required tabindex="3"',
				label: t('Y un apodo de al menos 3 caracteres'),
				placeholder: t('Aquí el apodo'),
				name: 'apodo', value: _var::post('apodo'))?>
			<br>
		</section>

		<section>
			<div class="auto">
				<a role="button" data-ajax=".ajax.show" href="/info/ventana/politicas" tabindex="4"><?=t('Ver políticas')?></a>	

				<a role="button" data-ajax=".ajax.show" href="/info/ventana/privacidad" tabindex="5"><?=t('Ver privacidad')?></a>
			</div>
			<br>
		</section>

		<footer>
			<label>
				<input type="checkbox" <?=_var::post('terminos')?'checked ':''?> name="terminos" tabindex="6" value="1">
				<em><?=t('Soy mayor de edad, acepto las políticas y solo entonces...')?></em>
			</label>
			<br>
			<?=Kubox::buttonSubmitColor(attrs: 'tabindex="7"',
				label: t('Me registro y voy al correo para confirmar la cuenta'),
				name: 'registrarse', value: 1)?>
			<br>
			<span><?=t('Si tienes algún problema para acceder podemos solucionarlo por...')?></span>
			<br>
			<div class="auto">
				<a href="https://t.me/demonio69" rel="noopener noreferrer" tabindex="8" target="_blank" title="Enlace para chatear por Telegram con Lobo Blanco">
					...Telegram
					&nbsp;
					<img alt="Icono de Telegram" src="/img/iconos/Telegram.svg" width="24" height="24">
				</a>
				<a href="https://web.whatsapp.com/send?phone=34603047311" rel="noopener noreferrer" tabindex="9" target="_blank" title="Enlace para chatear por WhatsApp al +34603047311">
					o WhatsApp
					&nbsp;
					<img alt="Icono de WhatsApp" src="/img/iconos/WhatsApp.svg" width="24" height="24">
				</a>
			</div>	
			<br>	
		</footer>
	</form>
	<br>
	<br>
	<br>
	<br>
</article>
