
<article>
    <header>
        <h1>Hola <?=$usuario->apodo?></h1>
    </header>

    <section>
        <p>El Escritorio Virtual 3.0 de R+ te permite crear todo lo que necesitas para jugar a rol.</p>
        <ul>
            <li>En el menú de arriba tienes acceso a las diferentes secciones, explóralas sin miedo a romper nada.</li>

            <li>En cada sección verás un menú a la izquierda con los elementos creados en esa sección.</li>
        </ul>
    </section>
</article>
