
<h1>Contenedores</h1>

<p>KumbiaCSS utiliza los mismos puntos de interrupción y tamaños de ventanas gráficas que Bootstrap.</p>

<figure>
    <table>
        <tr>
            <td>Dispositivo</td>
            <td>Extra Pequeño</td>
            <td>Pequeño</td>
            <td>Medio</td>
            <td>Grande</td>
            <td>Extra grande</td>
            <td>Extra extra grande</td>
        </tr>
        <tr>
            <td>Punto de interrupción</td>
            <td>&lt;576 px</td>
            <td>≥576 px</td>
            <td>≥768 px</td>
            <td>≥992 px</td>
            <td>≥1200 px</td>
            <td>≥1400 px</td>
        </tr>
        <tr>
            <td>Ventana gráfica</td>
            <td>100 %</td>
            <td>540 píxeles</td>
            <td>720 píxeles</td>
            <td>960 píxeles</td>
            <td>1140 píxeles</td>
            <td>1320 píxeles</td>
        </tr>
    </table>
</figure>
