
<h1>Desplazamiento horizontal</h1>

<p>&lt;figure> actúa como un contenedor para hacer que cualquier contenido se pueda desplazar horizontalmente:</p>

<?php _code::open('figure'); ?>
<figure>
    <table>
        …
    </table>
</figure>
<?php _code::close(); ?>

<p>Es útil para hacer responsivas las tablas:</p>

<figure>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
                <th>Título</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>1</th>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
            </tr>
            <tr>
                <th>2</th>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
            </tr>
            <tr>
                <th>3</th>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
                <td>Contenido</td>
            </tr>
        </tbody>
    </table>
</figure>
