
<h1>Inspiración</h1>

<p>Para crear KumbiaCSS nos hemos inspirado fuertemente en:</p>

<ul>
    <li>De <a href="https://m3.material.io">m3.material.io</a> nos hemos fijado en las medidas para que los elementos sean accesibles.</li>
    <li>De <a href="https://picocss.com">picocss.com</a> nos hemos fijado en su página web. Por su filosofía consideramos que es uno de los mejores marcos CSS con y sin clases.</li>
    <li>De <a href="https://open-props.style">open-props.style</a> hemos cogido prestadas algunas variables, pues nos encantan las variables.</li>
</ul>


