
<h1>Instalación</h1>

<p>¡Funciona sin administrador de paquetes ni dependencias 🙂!</p>

<p>Para incluirlo en su sitio web, descargue KumbiaCSS y enlácelo en su plantilla HTML:</p>

<?php _code::open('link'); ?>
<link rel="stylesheet" href="/css/kumbia.min.css">
<?php _code::close(); ?>

<p>Plantilla HTML inicial:</p>

<?php _code::open('template'); ?>
<!DOCTYPE html>
<html id="important" lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/kumbia.min.css">
        <title>Hello, world!</title>
    </head>
    <body>
        <main>
            <h1>Hello, world!</h1>
        </main>
    </body>
</html>
<?php _code::close(); ?>
