
<form enctype="multipart/form-data" method="post" action="/ev/manuales/<?= h($manual->idu ? 'actualizar' : 'crear') ?>">
    <section>
        <div class="grid">
            <label class="s3">
                <small><b><?= t('Formato') ?></b></small>
                <select name="formato">
                    <?php foreach (['a4' => 'A4', 'a5' => 'A5', 'letter' => 'Letter'] as $key => $val):
                        $selected = ($manual->formato == $key) ? 'selected' : ''; ?>
                        <option <?= $selected ?> value="<?= $key ?>"><?= $val ?></option>
                    <?php endforeach; ?>
                </select>
            </label>

            <label class="s3">
                <small><b><?= t('Orientación') ?></b></small>
                <select name="orientacion">
                    <?php foreach (['v' => t('Vertical'), 'h' => t('Horizontal')] as $key => $val):
                        $selected = ($manual->orientacion == $key) ? 'selected' : ''; ?>
                        <option <?= $selected ?> value="<?= $key ?>"><?= $val ?></option>
                    <?php endforeach; ?>
                </select>
            </label>

            <label class="s3">
                <small><b><?= t('Plantilla') ?></b></small>
                <input list="plantillas-list" name="plantilla" value="<?= h($manual->plantilla) ?>" placeholder="<?= t('Escribe o elige una...') ?>">
                <datalist id="plantillas-list">
                    <?php foreach ($plantillas as $pl): ?>
                        <option value="<?= h($pl->nombre) ?>"></option>
                    <?php endforeach; ?>
                </datalist>
            </label>

            <label class="s3">
                <small><b><?= t('Alcance') ?></b></small>
                <select name="alcance">
                    <?php foreach ([
                        'lectura' => t('Solo lectura'),
                        'privado' => t('Privado'),
                        'oculto' => t('Oculto'),
                        'editor' => t('Editor')
                    ] as $key => $val):
                        $selected = ($manual->alcance == $key) ? 'selected' : ''; ?>
                        <option <?= $selected ?> value="<?= $key ?>"><?= $val ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
        </div>

        <label>
            <small><b><?= t('Título') ?></b></small>
            <input type="text" name="nombre" placeholder="<?= t('Título del manual...') ?>" value="<?= h($manual->nombre) ?>">
        </label>

        <label>
            <small><b><?= t('Introducción') ?></b></small>
            <textarea name="introduccion" placeholder="<?= t('Texto para atraer a los máster...') ?>"><?= h($manual->introduccion) ?></textarea>
        </label>

        <small><b><?= t('Portada') ?></b></small>
        <label class="dropimage s12 <?= $manual->fotos ? 'dropnocontent' : '' ?>">
            <input type="file" name="imagenes[]">
            <button type="button" class="quitar" title="<?= t('Quitar imagen') ?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="9" x2="15" y2="15"></line><line x1="15" y1="9" x2="9" y2="15"></line></svg></button>
            <?php if ($manual->fotos): ?>
                <img alt="<?= t('Imagen del manual:') ?> <?= h($manual->nombre) ?>" src="/img/usuarios/<?= $manual->usuarios_idu ?>/l.<?= $manual->fotos ?>">
            <?php endif; ?>
        </label>

        <div class="s12 image-options">
            <?php if (!$manual->fotos): ?>
                <input type="hidden" name="fotos" value="<?= h($manual->fotos) ?>">
            <?php endif; ?>
        </div>

        <label>
            <small><b><?= t('Ficha') ?></b></small>
            <select name="fichas_idu">
                <option value=""><?= t('Escoge una...') ?></option>
                <?php foreach ($fichas as $fic):
                    $selected = ($manual->fichas_idu == $fic->idu) ? 'selected' : ''; ?>
                    <option <?= $selected ?> value="<?= $fic->idu ?>"><?= h($fic->nombre) ?></option>
                <?php endforeach; ?>
            </select>
        </label>
    </section>

    <footer class="grid">
        <?php if ($manual->idu): ?>
            <a role="button" class="outline" data-ajax=".ajax.show" href="/ev/manuales/formulario_manual"><?= t('Nuevo') ?></a>
            <button type="submit" class="outline" name="action" value="eliminar"><?= t('Eliminar') ?></button>
            <button type="submit" class="outline" name="action" value="crear"><?= t('Duplicar') ?></button>
            <button type="submit" name="action" value="actualizar"><?= t('Actualizar') ?></button>
            <input type="hidden" name="idu" value="<?= h($manual->idu) ?>">
        <?php else: ?>
            <a role="button" class="outline" href="/ev/manuales"><?= t('Manuales') ?></a>
            <button type="submit" name="action" value="crear"><?= t('Crear') ?></button>
        <?php endif; ?>
    </footer>
</form>
