<?php
$page = 'a4 landscape';
?>
<section>
    <div>
        <img class="mha" src="/img/editor/mundo_sencillo/logo.png">
        <h1>Mundo Sencillo</h1>
        <p><b>Un hack</b> simplificado y genérico <b>de Apocalypse World</b>.<br>
        Úselo bajo su propio riesgo.</p>

        <p>Creado <b>por Avery Alder</b> para su serie de pequeños juegos.</p>

        <p>Para más como este, visite:<br>
        <a href="https://buriedwithoutceremony.com/little-games" rel="noopener noreferrer" target="_blank">buriedwithoutceremony.com/little-games</a></p>

        <p>Dedicado a Vx.</p>

        <p><b>Traducido por Lobo Blanco</b> guardián de <a href="https://roleplus.app" rel="noopener noreferrer" target="_blank">roleplus.app</a> y <a href="https://mtgsearch.it" rel="noopener noreferrer" target="_blank">mtgsearch.it</a></p>
    </div>
    <div>
        <h2>Preparación del MC (Maestro de Ceremonias)</h2>
        <p><b>1) ¿De qué quieres que trate tu juego?</b> Responde a esa pregunta.</p>

        <p><b>2) Crea un atributo que refleje cada una de estas categorías:</b></p>

        <blockquote>✦ Reflexiva/Grácil<br>
        ✦ Persuasiva/Asertivo<br>
        ✦ Agresiva/Fuerte<br>
        ✦ Calculadora/Metódico<br>
        ✦ Inquisitiva/Curioso</blockquote>

        <p><b>3) Elimina o cambia un atributo;</b> Si alguna de esas categorías no importa para la historia que quieres contar, elimínala por completo (creando así 4 atributos) o inventa un atributo que refleje algo totalmente diferente.</p>

        <blockquote>Vx quiere usar Mundo Sencillo para jugar a un juego postapocalíptico. Crea los atributos: <b>Frío</b> (reflexiva/grácil), <b>Vivo</b> (persuasiva/asertivo), <b>Duro</b> (agresiva/fuerte), <b>Fino</b> (calculadora/metódico) y <b>Raro</b> (inquisitiva/curioso).</blockquote>

        <blockquote>Courtney quiere usar Mundo Sencillo para jugar a un juego de "damiselas	montando unicornios en busca de aventuras". Crea los atributos: <b>Graciosa</b> (reflexiva/grácil), <b>Encantadora</b> (persuasiva/asertivo), <b>Osada</b> (agresiva/fuerte), <b>Astuta</b> (calculadora/metódico) e <b>Indagadora</b> (inquisitiva/curioso).</blockquote>

        <p><b>4) Escribe los atributos en la hoja de personaje de cada jugador.</b></p>

        <p><b>5) Toma un montón de tarjetas. Escribe</b> un título evocador en cada una; <b>un tipo de persona interesante</b> sobre la que quieras contar historias. Esto son trasfondos para los personajes. <b>Y</b> debajo del título, lista <b>tres especialidades</b> propias del trasfondo <b>en cada tarjeta</b>.</p>

        <blockquote>Vx escribe <b>Cerebro</b> (controlar la mente, jugar con el peligroso poder psíquico, observador), <b>Vigilante</b> (controlar lacayos, proteger al pueblo, hacer trueques), <b>Conductor</b> (conducir coches, actuar desinteresadamente, asediar) y <b>Pensador</b> (romper y arreglar cosas, descubrir los claves del universo).</blockquote>
    </div>
</section>

<section>
    <div>
        <blockquote>Courtney escribe <b>Princesa</b> (liderar a mis camaradas, hechizar coraje, tirar con arco), <b>Doncella</b> (apoyar a mis camaradas, curar con magia, emplear subterfugios), <b>Bruja</b> (vencer el mal, maldecir, hablar con fantasmas) y <b>Halconera</b> (asediar, reconocer, tomar decisiones despiadadas).</blockquote>

        <p><b>6)</b> A continuación, echa un vistazo a tu Agenda / Principios / Movimientos del MC.</p>

        <p><b>Las Agendas</b> son las razones por las que juegas.</p>

        <p><b>Las dos primeras ya están rellenadas. Rellena una tercera:</b><br>
        ✦ Haz que la vida de los personajes de los jugadores no sea aburrida.<br>
        ✦ Juega para averiguar qué pasa a continuación.<br>
        ✦</p>

        <p><b>7) Los Principios</b> son cosas que debes procurar hacer siempre que hables, en el juego. Hay una lista rellenada para ti, esperando a que la personalices. Utiliza esta oportunidad de personalización para establecer la forma en que planeas dirigir el juego.</p>

        <p><b>Tacha hasta dos de estos Principios y escribe hasta dos propios:</b><br>
        ✦ Esparce detalles evocadores por todas partes.<br>
        ✦ Haz que el mundo parezca real.<br>
        ✦ Construye un mundo más grande a través del juego.<br>
        ✦ Crea dilemas interesantes, no tramas interesantes.<br>
        ✦ Dirígete a los personajes, no a los jugadores.<br>
        ✦ Haz tu movimiento, pero cambia de foco.<br>
        ✦ Haz tu movimiento, pero nunca digas su nombre.<br>
        ✦ No te apegues a tus PNJ e ideas.<br>
        ✦ Dale un nombre a todo y será importante.<br>
        ✦ Haz preguntas provocadoras y construye a partir de las respuestas.<br>
        ✦ Responde con circunstancias desafiantes y recompensas ocasionales.<br>
        ✦ Sé fan de los personajes de los jugadores.<br>
        ✦ Piensa también fuera de escena.<br>
        ✦ A veces, devuelve una pregunta a los jugadores.<br>
        ✦<br>
        ✦</p>
    </div>
    <div>
        <p><b>Los movimientos del MC</b> son las cosas específicas que dices en cada momento. Hay dos casos diferentes en los que usas los movimientos del MC, y los usas de forma diferente en cada caso. <b>Cuando los jugadores te miran expectantes, haces un movimiento del MC normal. Cuando un jugador falla una tirada</b> (obteniendo un 6 o menos), <b>haces un movimiento del MC duro.</b> John Harper describió mejor cómo manejar estos dos casos, así que lo citaré:</p>

        <p><b>Cuando haces un movimiento del MC normal, sucede esto:</b><br>
        1. Se desprende lógicamente de la ficción.<br>
        2. Da al jugador la oportunidad de reaccionar.<br>
        3. Te prepara para un futuro movimiento duro.</p>

        <p>✦ Di lo que pasa pero detente antes del efecto, luego pregunta "¿Qué haces?".</p>

        <p><b>Cuando haces un movimiento MC duro, sucede esto:</b><br>
        1. Se deriva lógicamente de la ficción.<br>
        2. Es irrevocable.</p>

        <p>✦ Di lo que ocurre, incluido el efecto, y luego pregunta "¿Qué haces?".</p>

        <p><b>8) Tacha hasta tres movimientos y añade hasta tres tuyos:</b><br>
        ✦ Sepáralos.<br>
        ✦ Júntalos.<br>
        ✦ Pon a alguien en una situación de alto riesgo.<br>
        ✦ Intercambia daño por daño (según lo establecido).<br>
        ✦ Haz daño (según lo establecido).<br>
        ✦ Anuncia algo malo fuera de escena.<br>
        ✦ Anuncia algo malo a futuro.<br>
        ✦ Quítales una de sus cosas.<br>
        ✦ Indica el lado malo de una de sus cosas.<br>
        ✦ Ofrece una decisión difícil.<br>
        ✦ Explica las posibles consecuencias y pregunta.<br>
        ✦ Usa uno de sus movimientos en su contra.<br>
        ✦ Haz un movimiento de uno de tus peligros o peligro mayor.<br>
        ✦<br>
        ✦<br>
        ✦</p>
    </div>
</section>

<section>
    <div>
        <blockquote>Vx añade "Erosionar todo el status quo" como su agenda final. En los principios, tacha "Construye un mundo más grande a través del juego", ya que su visión implica pequeñas comunidades y muy poca estructura social a nivel global. También tacha "Esparcir detalles evocadores por todas partes" para sustituirlo por uno más específico y temático "Vomitar decadencia apocalíptica". En los movimientos del MC, tacha "Júntalos" y añade "Captura a alguien" y "Indica una escasez importante".</blockquote>

        <blockquote>Courtney añade "Haz que hacer lo correcto sea difícil para los personajes de los jugadores" como su agenda final. En los principios, tacha "No te apegues a tus PNJ e ideas" y escribe "Permite que tus PNJ cambien y se desarrollen en las direcciones esperadas". En los movimientos del MC, tacha "Intercambia daño por daño (según lo establecido)" y "Haz daño (según lo establecido)". Y añade "Introduce un nuevo obstáculo para continuar" y "Destruye algo valioso (según lo establecido)".</blockquote>

        <p><b>9)</b> Por último, <b>cada PJ</b> del juego <b>tiene un atributo de relación con todos</b> los demás personajes. <b>Puedes llamar a este atributo como quieras</b>, o simplemente llámalo "Relaciones". Cuando ayudas a alguien o le entorpeces, eso tiene su propio movimiento básico, y tiras con el atributo de relación.</p>

        <h3>Ayudar y entorpecer a un PJ</h3>
        <p><b>Cuando ayudes a alguien o le pongas trabas, tira 2d6 más tu atributo de relación con esa persona:</b><br>
        ✦ Con 10 o más, suma o resta 2 a su tirada.<br>
        ✦ De 7 a 9, el maestro de ceremonias te impondrá un coste; si lo aceptas, suma o resta 2 a su tirada.</p>

        <h3>Ayudar y entorpecer a los PNJ</h3>
        <p><b>Cuando ayudes u obstaculices a alguien, tira 2d6 más tu atributo de relación con esa persona:</b><br>
        ✦ Con 10 o más, tendrá éxito o fracasará, tú eliges.<br>
        ✦ De 7 a 9, el maestro de ceremonias te impondrá un coste; si lo aceptas, la persona tendrá éxito o fracasará, a tu elección.</p>
    </div>
    <div>
        <p>Al comienzo de la partida, cada jugador asignará las siguientes puntuaciones al atributo de relación, que su personaje tiene hacia los otros PJ: +2 para el que mejor conozca, -1 para el que menos conozca y +1 para todos los demás. La relación con los PNJ empieza a 0 por defecto.</p>

        <p><b>Las puntuaciones de relación subirán y bajarán a lo largo del juego. Elige cómo:</b><br>
        ✦ Al final de cada sesión, cada jugador puede subir o bajar en 1 la puntuación de un PJ.<br>
        ✦ Cada vez que dos personajes tienen una escena especial juntos, sus puntuaciones aumentan en 1. Cada vez que dos personajes se enfrentan públicamente, sus puntuaciones disminuyen en 1.<br>
        ✦ Los personajes pueden traicionarse el uno al otro para obtener un +2 a una tirada, pero su puntuación de relación bajará en 1. Los personajes pueden hacer sacrificios significativos por alguien, y su puntuación de relación hacia esa persona subirá en 1.<br>
        ✦ Si quieres, inventa otra manera de alterar las relaciones.</p>

        <blockquote>Vx llama a su puntuación de relación "Hx". Decide que al final de cada sesión, cada jugador puede subir o bajar en 1 la puntuación de un PJ.</blockquote>

        <blockquote>Courtney llama a su atributo de relación "Amistad". Ella decide crear su propio sistema para alterar las relaciones. Cada PJ anota una virtud en su hoja de personaje (Esperanza, Justicia, Valentía...). Cuando otro PJ muestra esa virtud, la relación que mantiene con ese PJ aumenta en 1. Cuando otro PJ contradice esa virtud, la relación que mantiene con ese PJ disminuye en 1.</blockquote>

        <blockquote>Joe está escribiendo un juego de Mundo Sencillo sobre el drama de los monstruos adolescentes. Decide que el atributo de relación baje cada vez que lo tires, y que suba cada vez que ganes influencia emocional sobre un personaje (¡incluidos los PNJ!).</blockquote>

        <p>Y ya está. Tienes atributos, trasfondos para personajes, agendas, principios, movimientos y un atributo de relación. Estás listo para juntar un grupo y jugar.</p>
    </div>
</section>

<section>
    <div>
        <h2>Creando Personajes</h2>
        <p><b>Escribe en las hojas de personaje los nombres de los atributos y cómo el atributo de relación altera su valor:</b> Entrega a cada jugador una hoja de personaje. Debe tener los nombres de los atributos enumerados, incluido el atributo de relación. Debe tener una descripción de cómo el atributo de relación sube y baja a lo largo del juego.</p>

        <p><b>Cada personaje debe vincularse a un trasfondo diferente entre todos los disponibles:</b> Coloca los trasfondos de personajes en el medio de la mesa. Habla sobre lo que podrían significar y por qué podrían ser geniales. Que todos elijan uno y fíjelo a su hoja de personaje usando un clip de papel.</p>

        <p><b>Diles que asignen los siguientes números a sus 5 atributos:</b> +2, +1, +1, 0, -1. Si solo tienen 4 atributos, en su lugar asignen: +2, +1, 0, -1.</p>

        <p><b>El máximo que un atributo</b> puede alcanzar en el juego <b>es +3, y el mínimo es -1</b>. Esto incluye el atributo de relación. Los movimientos de los jugadores solo pueden avanzar un atributo más allá de +3 temporalmente.</p>

        <p><b>Cada PJ tiene un atributo de relación con cada otro PJ.</b> Diles a los jugadores que hagan esto: "elije <b>el PJ que mejor conozcas</b> y escribe <b>+2</b> junto al nombre de ese personaje. <b>El PJ que conozcas menos</b>, pon un <b>-1</b> junto a ese personaje. Para <b>cada otro PJ</b>, escribe <b>+1</b>. Escribe <b>PNJ</b> tantos como quieras y asigna la relación <b>a 0</b>".</p>

        <p><b>Cada personaje tiene un reloj de daño</b>, con seis secciones. Cuando los personajes reciben daño en el juego, marcan un número de secciones igual a la cantidad de daño que el MC les dice que reciben. Señala el reloj de daño y <b>explica que cuando está lleno, los personajes salen de la acción</b> (de una manera apropiada para el tipo de juego).</p>

        <p>La siguiente etapa <b>cada jugador registra en su hoja de personaje tres movimientos de la siguiente lista, le da un nombre a cada movimiento y reemplaza las variables</b> entre corchetes por aquello que sugieren.</p>
    </div>
    <div>
        <h3>Movimientos propios</h3>
        
        <p>✦ Cuando hagas algo relacionado con tu [especialidad], agrega +1.<br>
        ✦ Tienes la habilidad de [realizar algún tipo de poder especial activo]. Esto cuenta como un movimiento básico utilizando un [atributo].<br>
        ✦ Tienes [algún poder especial pasivo que tiene un efecto constante].<br>
        ✦ Tienes un [objeto]; +1 a [atributo] y a [atributo] cuando lo uses.<br>
        ✦ Cuando hagas tu [especialidad], ganas 1 PX (punto de experiencia).<br>
        ✦ Agrega +1 a un [atributo].</p>

        <blockquote>Mark está jugando en el juego apocalíptico de Vx. Elige a Cerebro y lo llama Wendigo. Le da a Wendigo los atributos: Frío -1, Vivo 0, Duro +1, Fino +1, Raro +2. Decide que tiene un Hx de +2 con Blink y un Hx de -1 con Rolfball. Crea los siguientes tres movimientos propios:</blockquote>

        <blockquote><b>Secretos sucios:</b> Tienes la habilidad de detectar la vergüenza secreta de alguien. Es un movimiento básico que usa Raro.</blockquote>

        <blockquote><b>Cadenas mentales:</b> Cuando hagas algo relacionado con el control mental, agrega +1 a la tirada.</blockquote>

        <blockquote><b>Abre tu mente:</b> Cuando haces eco del torbellino psíquico, ganas 1 PX.</blockquote>

        <blockquote>Lane está jugando en el juego de los unicornios de Courtney. Llama a su damisela Lucinda con Graciosa +1, Encantadora +2, Osada 0, Astuta +1 e Indagadora -1. Elige la virtud "Valor" para su atributo de relación. Decide que conoce mejor a Mercury, y escribe "Mercury +2". A Helena la conoce menos, "Helena -1". Eso deja a Ofelia, con una relación de +1. A Lucinda se le dan los siguientes tres movimientos propios:</blockquote>

        <blockquote><b>Sin miedo:</b> Cuando hagas algo relacionado con liderar a tus compañeros, agrega +1 a la tirada.</blockquote>

        <blockquote><b>Francotirador:</b> Cuando uses tiro con arco, agrega +1.</blockquote>

        <blockquote><b>Cuerno de poder ancestral:</b> Tienes un cuerno con un poder ancestral. Cuando sea aplicable, agrega +1 a Encanto.</blockquote>
    </div>
</section>

<section>
    <div>
        <p>Finalmente, <b>cada PJ va a tener dos atributos destacados. Cada jugador</b> (excepto el MC) elige y <b>destaca un atributo para el PJ a su izquierda. Luego, el MC destaca un segundo atributo de cada PJ</b>.</p>

        <p><b>Cuando se destaca un atributo, se marca la casilla junto al atributo.</b><br>
        ✦ Cuando un PJ tira con su atributo destacado, gana 1 PX.</p>

        <h2>Jugando el juego</h2>
        <br>
        <h3>El juego del MC</h3>

        <p>Al principio de la primera sesión, el MC debe manejar dos responsabilidades:</p>
        
        <p>✦ Permanece atento a los PJ y aprende todo sobre ellos.<br>
        ✦ Da a los jugadores una idea de cómo es y funciona el mundo.</p>

        <p>Los jugadores astutos se darán cuenta de que estas dos cosas a veces pueden contradecirse. MC, la forma en que navegas esta combinación de responsabilidades es honrando tus Agendas y tus Principios.</p>

        <h3>Conversación y Movimientos</h3>

        <p>El juego es como una conversación. La gente describe lo que hacen sus personajes, hacen preguntas sobre lo que está sucediendo y hablan en personaje. Si alguien dice algo que parece falso o irrazonable, el MC puede decir: "No creo que eso sea posible, pero en cambio podrías hacer [sugerencia interesante], si quieres".</p>
 
        <p>En algún momento, el MC determinará que algo requiere tirar los dados. Las acciones requieren una tirada de dados cuando se oponen a otros personajes o se arriesgan a un fracaso interesante. Cuando se cumple una de estas condiciones, el jugador activa uno de sus movimientos básicos. El MC dirá qué atributo se aplica a la situación, el jugador lanza dos dados de seis caras y suma ese atributo al resultado. Los efectos dependen del movimiento básico en cuestión.</p>
    </div>
    <div>
        <h2>Movimientos básicos</h2>

        <p>Hay tres movimientos básicos.</p>
        <br>
        <h3>Tomar acción</h3>
        <p><b>Cuando tomas una acción que conlleva el riesgo de fracasar o de oposición, tira 2d6 más un atributo apropiado:</b><br>
        ✦ Con 10 o más, tienes éxito en tu objetivo. Además el MC podría darte: puntos de recurso, hacer daño o una bonificación a la siguiente tirada.<br>
        ✦ De 7 a 9, el MC te ofrecerá un trato difícil o un coste. Si lo aceptas, tienes éxito en tu objetivo (y según corresponda, el MC podría darte: puntos de recurso, hacer daño o una bonificación a la siguiente tirada).</p>
        <br>
        <h3>Ayudando/Impidiendo a un PJ</h3>
        <p><b>Cuando ayudas o impides a alguien, tira 2d6 más tu atributo de relación con esa persona:</b><br>
        ✦ Con 10 o más, suma o resta 2 de su tirada.<br>
        ✦ De 7 a 9, el MC te ofrecerá un coste; si lo aceptas, suma o resta 2 de su tirada.</p>
        <br>
        <h3>Ayudando/Impidiendo a un PNJ</h3>
        <p><b>Cuando ayudas o impides a alguien, tira 2d6 más tu atributo de relación con esa persona:</b><br>
        ✦ Con 10 o más, ellos tienen éxito o fracasan a tu elección.<br>
        ✦ De 7 a 9, el MC te ofrecerá un coste; si lo aceptas, ellos tienen éxito o fracasan a tu elección.</p>
        <hr>
        <p>✦ Cuando sacas 6 o menos en un movimiento básico, el MC puede hacer un movimiento duro.</p>
    </div>
</section>

<section>
    <div>
        <p>Los movimientos (tanto los básicos como los del MC) deben impulsar continuamente el juego de manera interesante. Cuando un jugador tiene éxito en un movimiento básico, su éxito debe ser interesante e introducir nuevas oportunidades para ellos. Cuando un jugador obtiene de 7 a 9 en un movimiento básico, el dilema y la difícil negociación deben crear un drama convincente, y ambas opciones deben ser interesantes y llevar la historia a nuevas direcciones. Cuando un jugador falla en un movimiento básico, el MC debe responder con un movimiento duro del MC que cambie fundamentalmente la situación y exija nuevos tipos de acción.</p>

        <p>Cada vez que las personas miren al MC expectantes, el MC debe hacer un movimiento normal del MC. Esto debe crear nuevas cosas para que los jugadores reaccionen. El MC luego debe continuar diciendo: "Entonces, ¿qué haces?"</p>

        <h2>Puntos de recurso</h2>

        <p>Cuando alguien tiene éxito (con 10 o más, o de 7 a 9) en un movimiento de "Tomar acción", a veces tendrá sentido representar su éxito con una cantidad de puntos de recurso. Por ejemplo, si alguien intenta leer las expresiones faciales de una persona para determinar su verdadera intención de una conversación, puede hacer una tirada. Si obtienen un 10 o más, el MC podría determinar que tienen 3 puntos de conversación y pueden gastar esos puntos uno por uno para obtener respuestas sobre las motivaciones y objetivos del personaje durante la conversación. Estos puntos de recurso siempre tienen un nombre y una función en el momento en que se otorgan. En la mayoría de los casos, los puntos de recurso duran hasta el final de una escena o situación.</p>

        <blockquote>En el juego de Vx, Wendigo (el Cerebro) decide intentar controlar mentalmente a un comerciante errante para que simplemente entregue ciertos bienes. El MC dice: "Bueno, eso pide una tirada, porque el comerciante obviamente se opone a eso. ¿Aplica Raro aquí, verdad?", el atributo de Raro de Wendigo es 2, y tiene el movimiento de "Cadenas mentales" (Cuando haces algo relacionado con el control mental, agrega +1). ¡Obtiene un 2 y un 5 y lo suma al +3 de su atributo y movimiento. ¡Un 10! El MC dice: "Bien, tienes dos puntos de control mental. Puedes gastarlos uno por uno para obligarle a obedecer una orden psíquica o padecer 1 daño."</blockquote>
    </div>
    <div>
        <blockquote>En el juego de Courtney, Lucinda (la damisela) decide liderar a sus compañeros para cargar con sus unicornios hacia el castillo del ogro! Desafortunadamente tiene el atributo Osada a 0, pero tiene un movimiento que se aplica: Intrépido (Cuando haces algo relacionado con [dirigir a tus compañeros], añade +1). Ella obtiene un total de 7. El MC dice: "De acuerdo, pero te propongo esta complicación: mientras cargas, los centinelas del ogro interponen sus mazas con pinchos. Puedes avanzar, pero tu unicornio resultará herido y necesitarás curarlo". Lucinda acepta y el MC dice: "De acuerdo, voy a otorgarte tres puntos de táctica. Puedes gastarlos para hacer cosas como: reunir a los centinelas, asegurar que ningún ogro escape, asegurar que nadie más resulte herido, evitar que te acorralen o te rechacen, saber más sobre la situación, etc".</blockquote>

        <h2>Inflingir daño</h2>
        <p>Cuando alguien tiene éxito en una tirada de "Tomar acción", a veces tiene sentido que inflinga daño a su oposición. El daño suele ser daño físico causado por la violencia, pero puede variar según el contexto. Cuando alguien hace daño a otra persona, el MC valorará ese daño de 1 a 3. Lo que hace que una determinada puntuación varíe según el contexto. El daño de los PJ se marcará en el reloj de daño de su hoja de personaje. El daño de los PNJ lo anota el MC, ya sea en su cabeza o en sus notas. Los PNJ generalmente pueden soportar 2 daños antes de ser sacados de la acción, pero los PNJ más duros pueden soportar más.<p>

        <h2>Ser sacado de la acción</h2>
        <p>Cuando un personaje tiene todas sus secciones de daño llenas, es sacado de la acción. Los detalles variarán según el tipo de juego y su contexto. En un juego tipo Stranger Things, ser sacado de la acción significa desaparecer bajo circunstancias misteriosas (para despertar atado a una silla más tarde) o caer en coma. En un juego de pandillas apocalípticas, ser sacado de la acción significa ser asesinado. Cuando un personaje es sacado de la acción, ya no es jugable: o está muerto o algo equivalente. Si el personaje era un PJ, el jugador debería crear un nuevo personaje.</p>
    </div>
</section>

<section>
    <div>
        <blockquote>En el juego de Vx, Brink (el Conductor) decide atropellar a un matón que intenta obstaculizar la carretera. Él tira 2d6 más Duro, y obtiene un 10. El MC dice: "Genial. Definitivamente golpeaste a este tipo y escuchas un golpe debajo del auto. Un auto a esta velocidad definitivamente hace 2 daños, así que este tipo debería estar muerto o moribundo. La carretera está despejada. ¿Qué haces a continuación?"</blockquote>

        <h2>Bonificación para más adelante</h2>
        <p>A veces, tener éxito en una tirada de "Tomar Acción" significa que el PJ está inspirado. En estos casos, el MC puede dar un +1 para que el PJ lo pueda aplicar a su próxima tirada. El jugador debe marcar esta bonificación temporal en su hoja de personaje.</p>

        <blockquote>En el juego de Courtney, Helena (la Halconera) envía a sus halcones a explorar al mejor lugar para intentar cruzar los muros de la fortaleza. Esta es una tirada de "Tomar Acción", y Helena obtiene de un 7 a 9. El MC dice: "De acuerdo, tus halcones vuelan sobre la fortaleza, pero llaman la atención de los guardias. Si sigues adelante, te encontrarás con guardias armados y preparados contra ti. Pero los halcones identifican el mejor lugar para que intentes escalar los muros, cerca del matorral, donde el muro ha comenzado a desmoronarse. Tendrás un +1 para escalar el muro allí, si eliges hacerlo".</blockquote>

        <h2>Marcando PX</h2>
        <p>Cada vez que tiras tu atributo destacado, anota 1 PX en tu ficha. Cuando llegues a 5 PX, bórralos y escoge un nuevo movimiento propio para el personaje. Si ya tienes al menos un movimiento de estos que haga referencia a cada uno de tus especialidades, puedes crear una nueva especialidad y anotarla en la ficha.</p>
    </div>
    <div>
        <h2>Entre sesiones</h2>
        <p>Al final de cada sesión, los jugadores pueden ajustar los atributos de relación (si es así cómo fluctúan los atributos de relación en tu juego). Entre sesiones, el MC podría crear Peligros, y podría crear un "Peligro mayor" con esos Peligros. Al comienzo de cada sesión, los atributos destacados se cambian. Quien tenga la puntuación de relación más alta con un personaje elige un atributo para destacar, y el MC destaca un segundo atributo.</p>

        <h2>Peligros y "Peligro mayor"</h2>
        <p>Entre sesiones o durante de estas, el MC puede crear Peligros. Los Peligros son cosas que pueden causar problemas para los PJ, o luchar contra ellos por recursos, o bloquear el camino delos PJ. Cuando crees un Peligro, toma una tarjeta. Escribe su nombre, su Ambición y de 1 a 3 movimientos del MC. Su Ambición es lo que quiere y se esfuerza por lograr. Si los PJ no hacen nada para detener este Peligro, la Ambición se llevará acabo con efectos desastrosos. Los movimientos del MC son cosas que el MC puede hacer de su lista de movimientos cada vez que el Peligro se hace presente.</p>

        <blockquote>En el juego postapocalíptico de Vx, él crea un Peligro llamado "Morken el grotesco". Su Ambición es "Acumular lo valioso en el desierto andrajoso". Sus movimientos del MC son "Mostrar la naturaleza del mundo en el que habita, Amenazar a alguien, directa o indirectamente y Robar algo a alguien". Cada vez que Morken esté en la escena, esas tres cosas son cosas que Vx puede hacer como movimientos del MC.</blockquote>

        <blockquote>En el juego de damiselas sobre unicornios de Courtney, ella crea un Peligro llamado "Los Pantanos de la simetría". Su Ambición es "Eliminar los números impares y lo descompensado". Sus movimientos del MC son "Encerrar a la gente en un lugar remoto, Ocultar la salida e Intentar tragarse a la gente viva".</blockquote>
    </div>
</section>

<section>
    <div>
        <p>Si tienes varios peligros que cooperan juntos, puedes agruparlos en un "Peligro mayor". Toma una tarjeta y dóblala por la mitad. Ahora actúa como una carpeta en la que puedes meter los peligros con intereses comunes. En la parte frontal de esta tarjeta, escribe el nombre del "Peligro mayor". En las mitades interiores, escribe un nuevo Principio y un "Futuro oscuro". El Principio es algo que debes hacer siempre que este "Peligro mayor" esté involucrado en una escena. El "Futuro oscuro" es una lista de posibilidades de lo que podría suceder si los PJ no interfieren con el "Peligro mayor".</p>

        <blockquote>Vx decide que Morken no es la única amenaza en el desierto andrajoso. Así que él crea un "Peligro mayor" llamado "El desierto andrajoso". En él, Vx agrupa tres peligros relacionados: Morken el grotesco; La banda del trueno; Sierpes andrajosas. Crea un Principio común para cuando los PJ están interactuando en el desierto andrajoso: "Seducir a la gente con propuestas peligrosas". Como "Futuro oscuro", Vx escribe "El desierto andrajoso se expandirá, convirtiéndose en un reino peligroso e impenetrable de ladrones y mutantes".</blockquote>

        <img class="mha" src="/img/editor/mundo_sencillo/peligro_mayor.png">
    </div>
    <div>
        <h2>Tipo de juego y decisiones del MC</h2>

        <p>El MC tendrá que tomar una serie de decisiones antes y durante el juego. La preparación del MC antes del juego (nombrar atributos, modificar agendas, principios, movimientos del MC, aclarar el atributo de relación) implica una gran cantidad de decisiones sobre tipo de juego y su tono. Más decisiones de este tipo se harán durante el juego.</p>

        <p>El MC tendrá que tomar decisiones sobre qué requiere una tirada para "Tomar Acción" y qué es completamente imposible según el tipo de juego propuesto. El MC debe usar su derecho a veto con prudencia y moderación. Si alguien quiere tomar una acción que subvierta el tipo de juego, ¡eso es bueno!, pero cuando quieran tomar una acción que no sea posible o absurda para el tipo de juego dado es cuando el MC debería decir algo como esto: "No creo que sea posible, pero podrías hacer [sugerencia interesante], si lo deseas".</p>

        <p>Cuando alguien tiene todas las secciones de su reloj de daño llenas, queda juera de juego. Lo que esto significa depende del tipo de juego y el contexto. En un juego de aventuras de lucha, esto normalmente significará que son asesinados o capturados por fuerzas antagónicas feroces. ¡El MC no debe andarse con rodeos cuando saca a alguien de la acción! Debe hacerse de la manera más dramática, severa y permanente que tenga sentido para el tipo de juego y el contexto.</p>
        <br>
        <br>
        <div class="align-right float-right">
            <img src="/img/editor/mundo_sencillo/logo.png" width="200">
            <h2>Fin</h2>
        </div>
    </div>
</section>

<section>
    <div>
        <h2>Hoja de preparación del MC</h2>
        <br>
        <h3>Los atributos</h3>
        <br>
        <table>
            <tr>
                <td>✦ Reflexiva/Grácil</td>
                <td>__________________</td>
            </tr>
            <tr>
                <td>✦ Persuasiva/Asertivo</td>
                <td>__________________</td>
            </tr>
            <tr>
                <td>✦ Agresiva/Fuerte</td>
                <td>__________________</td>
            </tr>
            <tr>
                <td>✦ Calculadora/Metódico</td>
                <td>__________________</td>
            </tr>
            <tr>
                <td>✦ Inquisitiva/Curioso</td>
                <td>__________________</td>
            </tr>
        </table>
        <br>
        <h3>Agendas</h3>
        <br>
        <p><b>Las dos primeras ya están rellenadas. Rellena la tercera:</b><br>
        ✦ Haz que la vida de los personajes de los jugadores no sea aburrida.<br>
        ✦ Juega para averiguar qué pasa a continuación.<br>
        ✦</p>
        <br>
        <h3>Atributo de relación __________________</h3>
        <br>
        <br>
        <br>
        <h3>Cómo cambia el valor de una relación:</h3>
        <br>
        <div class="bordered" style="width:400px; height:200px"></div>
    </div>
    <div>
        <h3>Principios</h3>
        <br>
        <p><b>Tacha hasta dos de estos Principios y escribe hasta dos propios:</b><br>
        ✦ Esparce detalles evocadores por todas partes.<br>
        ✦ Haz que el mundo parezca real.<br>
        ✦ Construye un mundo más grande a través del juego.<br>
        ✦ Crea dilemas interesantes, no tramas interesantes.<br>
        ✦ Dirígete a los personajes, no a los jugadores.<br>
        ✦ Haz tu movimiento, pero cambia de foco.<br>
        ✦ Haz tu movimiento, pero nunca digas su nombre.<br>
        ✦ No te apegues a tus PNJ e ideas.<br>
        ✦ Dale un nombre a todo y será importante.<br>
        ✦ Haz preguntas provocadoras y construye a partir de las respuestas.<br>
        ✦ Responde con circunstancias desafiantes y recompensas ocasionales.<br>
        ✦ Sé fan de los personajes de los jugadores.<br>
        ✦ Piensa también fuera de escena.<br>
        ✦ A veces, devuelve una pregunta a los jugadores.<br>
        ✦<br>
        ✦</p>
        <br>
        <h3>Movimientos del MC</h3>
        <br>
        <p><b>Puedes tachar hasta tres movimientos y añadir hasta tres propios:</b><br>
        ✦ Sepáralos.<br>
        ✦ Júntalos.<br>
        ✦ Pon a alguien en una situación de alto riesgo.<br>
        ✦ Intercambia daño por daño (según lo establecido).<br>
        ✦ Haz daño (según lo establecido).<br>
        ✦ Anuncia algo malo fuera de escena.<br>
        ✦ Anuncia algo malo a futuro.<br>
        ✦ Quítales una de sus cosas.<br>
        ✦ Indica el lado malo de una de sus cosas.<br>
        ✦ Ofrece una decisión difícil.<br>
        ✦ Explica las posibles consecuencias y pregunta.<br>
        ✦ Usa uno de sus movimientos en su contra.<br>
        ✦ Haz un movimiento de uno de tus peligros o peligro mayor.<br>
        ✦<br>
        ✦<br>
        ✦</p>
    </div>
</section>

<section>
    <div>
        <hr>
        <h2>Hoja de personaje</h2>
        <table class="bordered float-right">
            <tr>
                <td><h3>Puntos de recurso</h3></td>
                <td style="width:40px; height:40px"></td>
            </tr>
        </table>
        
        <br>
        <br>
        <br>
        <div class="float-left" style="width: 30%">
            <h3>Name:</h3>
            <br>
            <br>
            <h3>Atributos:</h3>
            <table class="bordered">
                <tr>
                    <td style="width:200px; height:40px"></td>
                    <td style="width:40px"></td>
                    <td class="borderless">◯</td>
                </tr>
                <tr>
                    <td style="width:200px; height:40px"></td>
                    <td style="width:40px"></td>
                    <td class="borderless">◯</td>
                </tr>
                <tr>
                    <td style="width:200px; height:40px"></td>
                    <td style="width:40px"></td>
                    <td class="borderless">◯</td>
                </tr>
                <tr>
                    <td style="width:200px; height:40px"></td>
                    <td style="width:40px"></td>
                    <td class="borderless">◯</td>
                </tr>
                <tr>
                    <td style="width:200px; height:40px"></td>
                    <td style="width:40px"></td>
                    <td class="borderless">◯</td>
                </tr>
            </table>

            <img class="float-right" src="/img/editor/mundo_sencillo/reloj.png">

            <br>
            <h3>Experiencia:</h3>
            <table>
                <tr>
                    <td>&nbsp;1 &nbsp;</td>
                    <td>&nbsp;2 &nbsp;</td>
                    <td>&nbsp;3 &nbsp;</td>
                    <td>&nbsp;4 &nbsp;</td>
                    <td>&nbsp;5 &nbsp;</td>
                </tr>
                <tr>
                    <td>◯</td>
                    <td>◯</td>
                    <td>◯</td>
                    <td>◯</td>
                    <td>◯</td>
                </tr>
            </table>
            <small>Cuando vayas a marcar el 5 borra<br>
            todos y escoge un nuevo movimiento propio.</small>
        </div>

        <div class="float-left" style="width: 30%">
            <small><i>El atributo de relación es:</i></small>
            <table class="bordered">
                <tr>
                    <td style="width:240px; height:40px"></td>
                </tr>
            </table>
            <br>
            <br>
            <h3>Relaciones:</h3>
            <table class="bordered">
                <tr>
                    <td style="width:240px; height:40px"></td>
                    <td style="width:40px"></td>
                </tr>
                <tr>
                    <td style="width:240px; height:40px"></td>
                    <td style="width:40px"></td>
                </tr>
                <tr>
                    <td style="width:240px; height:40px"></td>
                    <td style="width:40px"></td>
                </tr>
                <tr>
                    <td style="width:240px; height:40px"></td>
                    <td style="width:40px"></td>
                </tr>
                <tr>
                    <td style="width:240px; height:40px"></td>
                    <td style="width:40px"></td>
                </tr>
                <tr>
                    <td style="width:240px; height:40px"></td>
                    <td style="width:40px"></td>
                </tr>
            </table>
        </div>

        <div class="float-left" style="width: 40%">
            <h3>Movimientos propios:</h3>
            <div class="bordered" style="width:100%; height:200px"></div>
            <table>
                <tr>
                    <td>
                        <small>✦ Cuando hagas algo relacionado con tu [especialidad], agrega +1.<br>
                        ✦ Tienes la habilidad de [realizar algún tipo de poder especial activo]. Esto cuenta como un movimiento básico utilizando un [atributo].<br>
                        ✦ Tienes [algún poder especial pasivo que tiene un efecto constante].</small>
                    </td>
                    <td>
                        <small>✦ Tienes un [objeto]; +1 a [atributo] y a [atributo] cuando lo uses.<br>
                        ✦ Cuando hagas tu [especialidad], ganas 1 PX (punto de experiencia).<br>
                        ✦ Agrega +1 a un [atributo].</small>
                    </td>
                </tr>
            </table>
        </div>
        <div class="clear"></div>
        <br>
        <hr>
        <h3>Tomar acción</h3>
        <br>
        <div class="float-left" style="width: 40%; padding-right:25px">
            <small>
                <p><b>Cuando tomas una acción que conlleva el riesgo de fracasar o de oposición, tira 2d6 más un atributo apropiado:</b><br>
                ✦ Con 10 o más, tienes éxito en tu objetivo. Además el MC podría darte: puntos de recurso, hacer daño o una bonificación a la siguiente tirada.<br>
                ✦ De 7 a 9, el MC te ofrecerá un trato difícil o un coste. Si lo aceptas, tienes éxito en tu objetivo (y según corresponda, el MC podría darte: puntos de recurso, hacer daño o una bonificación a la siguiente tirada).</p>
            </small>
        </div>
        <div class="float-left" style="width: 30%; padding-right:25px">
            <h3>Ayudando/Impidiendo a un PJ</h3>
            <br>
            <small>
                <p><b>Cuando ayudas o impides a alguien, tira 2d6 más tu atributo de relación con esa persona:</b><br>
                ✦ Con 10 o más, suma o resta 2 de su tirada.<br>
                ✦ De 7 a 9, el MC te ofrecerá un coste; si lo aceptas, suma o resta 2 de su tirada.</p>
            </small>
        </div>
        <div class="float-left" style="width: 30%">
            <h3>Ayudando/Impidiendo a un PNJ</h3>
            <br>
            <small>
                <p><b>Cuando ayudas o impides a alguien, tira 2d6 más tu atributo de relación con esa persona:</b><br>
                ✦ Con 10 o más, ellos tienen éxito o fracasan a tu elección.<br>
                ✦ De 7 a 9, el MC te ofrecerá un coste; si lo aceptas, ellos tienen éxito o fracasan a tu elección.</p>
            </small>
        </div>
    </div>
</section>
