<script src="https://accounts.google.com/gsi/client" async></script>

<div id="g_id_onload"
    data-client_id="787739430606-lnei8eglptva554e8a01e66st34cppig.apps.googleusercontent.com"
    data-context="signin"
    data-ux_mode="popup"
    data-login_uri="http://localhost/index/logged"
    data-auto_select="false"
    data-itp_support="true">
</div>

<?php
require_once VENDOR_PATH . 'autoload.php';
