<style>
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        margin-bottom: 0;
    }
    
    h4 {
        font-weight: unset;
    }
    
    ul {
        margin-top: 0;
        padding-left: 20px;
    }
</style>

<h1>Índice Revista Líder</h1>

<h3>Secciones fijas que no llevan sello</h3>

<ul>
    <li>Checklist de Contra la sombra: Nº61</li>
    <li>Checklist de Fallen Empires: Nº45</li>
    <li>Checklist de La mano blanca: Nº62</li>
    <li>Checklist de Los dragones: Nº54</li>
    <li>Checklist de Mythos: Nº53</li>
    <li>Coleman Charlton, el gran Istari: Nº53</li>
    <li>Como utilizar contra la sombra (o como mezclar SA con OsP): Nº61</li>
    <li>El despertar del ojo: Nº58</li>
    <li>El señor de los anillos: Nº49</li>
    <li>Elisabeth Garfield. El encuentro: Nº47</li>
    <li>El consultorio del mago frustrado: Nº52, Nº54, Nº55</li>
    <li>El rincón del Istar: Nº52, Nº53, Nº54, Nº55, Nº57, Nº61</li>
    <li>El ojo sin párpado: por fin puedes ser malo: Nº59</li>
    <li>El ojo sin párpado: primeros (y nuevos) pasos: Nº60</li>
    <li>Ice age: Nº48</li>
    <li>La ira del dragón: Nº48</li>
    <li>La mano blanca: reniega de Sauron y de los pueblos libres: Nº62</li>
    <li>Las cartas de Cthulhu: Nº54</li>
    <li>Lista completa de cartas de "El ojo sin párpado": Nº60</li>
    <li>Lista de cartas de Mythos: Nº56</li>
    <li>Magic, la 4ª edición: Nº48</li>
    <li>Magic, las dudas: Nº47</li>
    <li>Magic, the gathering.Un poco de todo: Nº49</li>
    <li>Magic, the gathering. Reglas de torneo: Nº46</li>
    <li>Marvel overpower: Nº49</li>
    <li>Mythos, comodines en la manga: Nº62</li>
    <li>Mythos, diseñar una baraja: Nº58, Nº59, Nº60</li>
    <li>Mythos, el juego básico: Nº57</li>
    <li>Re cuor di leone, la spaguetti-card: Nº47</li>
    <li>Servidores de la oscuridad: Nº56</li>
    <li>Servidores de la oscuridad: el alargado brazo de sauron: Nº57</li>
    <li>Siete anillos para los señores enanos en casas de piedra..: Nº52</li>
    <li>...nueve anillos para los hombres mortales condenados a morir: Nº56</li>
    <li>SATM. Los dragones: Nº53</li>
    <li>SATM. Un viaje de ida y vuelta: Nº51</li>
    <li>The great Dalmuti: Nº49</li>
    <li>The last crusade: Nº52</li>
    <li>Torneo Istari día de joc: Nº53</li>
    <li>Torneos en día de joc: Nº59</li>
    <li>Un anillo que los gobierna a todos... Primer campeonato del mundo de SATM: Nº58</li>
    <li>Wargames en cartas: la mejor defensa es un buen ataque: Nº49</li>
</ul>

<h4>A primera vista: Nº47, Nº48, Nº49, Nº50, Nº51, Nº52, Nº53, Nº54, Nº55, Nº56, Nº57, Nº58, Nº59, Nº60, Nº61, Nº62</h4>

<h4>Base Echo / En una galaxia lejana: Nº40, Nº54, Nº58</h4>

<h4>Consultorio de Pepe Goblin: Nº17</h4>

<h4>Consultorio del Orco Francis: Nº1, Nº2, Nº3, Nº4, Nº5, Nº6, Nº7, Nº9, Nº10, Nº11, Nº12, Nº13, Nº14, Nº15, Nº16, Nº18, Nº19, Nº20</h4>

<h4>Consultorio del Orco Francis</h4>
<ul>
    <li>A la playa con los dados: Nº24</li>
    <li>A todo esto... ¿Dónde están ellas? Nº29</li>
    <li>A un paso de los cincuenta: Nº49</li>
    <li>Amigo Francis ¿cómo te lo sirvo? Nº30, Nº31</li>
    <li>Begin the begin: Nº52</li>
    <li>Cambio de pareja: Nº41</li>
    <li>Como andar en bicicleta: Nº50</li>
    <li>De viajes a sitios exóticos: Nº60</li>
    <li>Encuentros en la tercera edad: Nº26</li>
    <li>Escaqueando: Nº61</li>
    <li>Eso no era un juego: Nº42</li>
    <li>Este año, por fin: Nº39</li>
    <li>Etiqueta en las jornadas: Nº59</li>
    <li>Fauna rolera: Nº38</li>
    <li>Fuera de partida: Nº57</li>
    <li>¿Qué hacer con algo tan bueno entre las manos? Nº21</li>
    <li>Jornadas, campeonatos y otros culebrones veraniegos: Nº48</li>
    <li>Jornadas y demás encuentros Nº34</li>
    <li>¿Jugar contigo? ¡Nunca más! Nº25</li>
    <li>La carta a los reyes: Nº62</li>
    <li>La locura del club: Nº22</li>
    <li>Los odio: Nº53</li>
    <li>Masters del universo: Nº54</li>
    <li>Ni fecha en el calendario: Nº58</li>
    <li>No hay color: Nº28</li>
    <li>Oscuro, demasiado oscuro: Nº51</li>
    <li>Ser o no ser: Nº55</li>
    <li>Sign of the times: Nº45</li>
    <li>Summon Orc. Edición especial Magic</li>
    <li>Pura improvisación: Nº43</li>
    <li>Pifias II, el regreso: Nº37</li>
    <li>Pifias III, "play it again, Sam": Nº44</li>
    <li>Sobre la complejidad de las reglas (o de cómo los árboles, muchas veces, no dejan ver el bosque): Nº47</li>
    <li>Solo si lo exige el guión: Nº33</li>
    <li>Sufragistas en la tierra media: Nº36</li>
    <li>Todos podemos ser DJs: Nº23</li>
    <li>Tiempo al tiempo: Nº46</li>
    <li>Torneos: Nº35</li>
    <li>Tramposos: Nº40</li>
    <li>Vamos a por ello: Nº27</li>
    <li>Y a todo esto... ¿Dónde están ellas? Nº29</li>
</ul>

<h4>El buzón de Gollum: Nº28, Nº44</h4>

<h4>El correo del Zar</h4>
<ul>
    <li>Air force por correo: Nº15</li>
    <li>D-Day por correo: Nº13</li>
    <li>Hegemonía. Diplomacy por correo en la Europa del S. XVIII: Nº20</li>
    <li>La tierra media: Nº46</li>
    <li>Les liaisons dangereuses: Nº52</li>
    <li>Panzer armee Afrika: Nº18</li>
    <li>Panzerblitz: Nº19</li>
    <li>Panzerkrieg por correo: Nº22</li>
</ul>

<h4>El pincel de Marta</h4>
<ul>
    <li>¿Otra vez cartas? Nº51</li>
    <li>Aquellos chalados con sus locos cacharros: Nº39</li>
    <li>Cartas y promesas: Nº44</li>
    <li>Colorín, colorado: Nº55</li>
    <li>Correspondencia: Nº43</li>
    <li>El oficio de artesano: Nº56</li>
    <li>En el campo de batalla: Nº62</li>
    <li>Estandartes para la victoria: Nº38</li>
    <li>Figura a piezas: Nº35</li>
    <li>Fuego en los pinceles: Nº41</li>
    <li>Hágala usted mismo: Nº40</li>
    <li>Introducción a los dioramas: Nº57</li>
    <li>Pintando ejércitos: Nº47</li>
    <li>Pintando figuras: Nº23, Nº24</li>
    <li>Transformación de figuras: Nº37</li>
    <li>Preparación de dioramas: Nº58</li>
    <li>Vinilo, vinilo: Nº45, Nº46</li>
    <li>Yggdrasil, 100% puro rol en vivo: Nº50</li>
</ul>

<h4>El tablero de cristal / Microjuegos</h4>
<ul>
    <li>Aventuras sin fin: Nº37</li>
    <li>Civilization: Nº33</li>
    <li>El frente del pacífico: Nº35</li>
    <li>El tablero de cristal: Nº22</li>
    <li>Enemigos a cola: Nº41</li>
    <li>Leisure suit Larry: Nº6</li>
    <li>Nuevos juegos para tu pantalla: Nº39</li>
    <li>Spacequest: Nº5</li>
    <li>Todos a las trincheras: Nº44</li>
    <li>Tolkien en CD-Rom: Nº40</li>
    <li>V for victory: Nº34</li>
    <li>Wizards crown: Nº7</li>
</ul>

<h4>Erratas de la guía imperial: Nº50</h4>

<h4>Europa-España: Nº12, Nº14, Nº16, Nº19, Nº21</h4>

<h4>Flechas contra corazas: Nº17, Nº18, Nº19, Nº21, Nº22, Nº24, Nº43</h4>

<h4>Guía para lobeznos (blancos). Stormbringer: Nº25, Nº29, Nº33, Nº39, Nº56, Nº62</h4>

<h4>Juegos de club/Nuestros juegos</h4>
<ul>
    <li>¡Acuñación! Nº51</li>
    <li>Apocalipsis: Nº61</li>
    <li>Appleseed: Nº61</li>
    <li>Atlantis Nº52</li>
    <li>Corporación: Nº62</li>
    <li>Dragon ball, Bola de dragón, Bola de drac, Dragoibola, As bolas maxicas,...Nº45</li>
    <li>Druidas: Nº59</li>
    <li>El Dajedrez nuclear: Nº44</li>
    <li>El santo eje: Nº40</li>
    <li>Exoesquad: Nº58</li>
    <li>Fokker: Nº40</li>
    <li>Guild, el juego de rol de Dune: Nº46</li>
    <li>Kalevala, la forja del héroe: Nº50</li>
    <li>Lemuria: Nº53</li>
    <li>Las garras del dragón: Nº49</li>
    <li>Los inmortales: Nº55</li>
    <li>Mercenarios: Nº58</li>
    <li>Ningunaterra: Nº40</li>
    <li>Omni ludi: Nº59</li>
    <li>Rock Star: Nº57</li>
    <li>Take your daughter to the slaughter: Nº53, Nº62</li>
    <li>Two worlds, 2ª edición: Nº47</li>
    <li>Urban tribes: Nº56</li>
    <li>X, la escalera: Nº57</li>
</ul>

<h4>La biblioteca de Ankh-Morpork: Nº17, Nº18, Nº19, Nº20, Nº21, Nº22, Nº23, Nº24, Nº25, Nº26, Nº27, Nº28, Nº29, Nº30, Nº31, Nº32, Nº34, Nº35, Nº36, Nº37, Nº38, Nº39, Nº40, Nº41</h4>

<h4>Las llamadas de Cthulhu: Nº7, Nº9, Nº10, Nº11, Nº12, Nº13, Nº14, Nº15, Nº16, Nº17, Nº18, Nº19, Nº20, Nº21, Nº23, Nº38, Nº49</h4>

<h4>Los secretos del diablo (Aquelarre): Nº21(Fe de erratas), Nº22, Nº24, Nº26, Nº27, Nº37, Nº41, Nº46, Nº51, Nº55, Nº57, Nº59, Nº61</h4>

<h4>Los secretos del diablo (INS/MV): Nº57</h4>

<h4>Plomo en las mesas</h4>
<ul>
    <li>Batallas fantásticas: Nº23</li>
    <li>Command decision: Nº28</li>
    <li>Dos ejércitos enfrentados, aparentemente iguales..: Nº8</li>
    <li>El combate que nunca existió: Nº36</li>
    <li>Espadas y pólvora. Reglas para la época del Renacimiento: Nº27</li>
    <li>Hacia el rugir de los cañones: Nº14</li>
    <li>La batalla de Cacabelos: Nº29</li>
    <li>La batalla de Cannas: Nº26</li>
    <li>La batalla de Cardedeu: Nº21</li>
    <li>La batalla de Cocherel: Nº15</li>
    <li>La batalla de Elviña: Nº11</li>
    <li>La batalla de Eyllau: Nº32</li>
    <li>La batalla de Lahn: Nº8</li>
    <li>La batalla de Kadesh: Nº7</li>
    <li>La batalla de Maratón: Nº13</li>
    <li>La batalla de Maya 25/07/1813: Nº18</li>
    <li>La batalla de Pidna 168 a. C: Nº19</li>
    <li>La batalla de Rocroi: Nº27</li>
    <li>La batalla de Rolica: Nº25</li>
    <li>La batalla de Salamina: Nº22</li>
    <li>La batalla de San Marcial: Nº12</li>
    <li>La batalla de Troyany: Nº37</li>
    <li>La batalla de Waterloo: Nº4</li>
    <li>La guerra civil americana: Nº8</li>
    <li>La guerra de los 100 años: La expedición navarra: Nº16</li>
    <li>Los últimos de Filipinas: Nº5</li>
    <li>¿Por qué hacer un juego de guerra de antigüedad con figuras?: Nº1</li>
    <li>Renacimiento: Nº6</li>
    <li>Retinue: Nº31</li>
    <li>Simulación con figuras. Reglas de asedios: Nº20</li>
    <li>Terminator: Nº30</li>
    <li>Ushutu! La batalla de Ishandlwana: Nº17</li>
    <li>Warhammer fantasy battle Nº34</li>
</ul>

<h4>Primera fila</h4>
<ul>
    <li>Acción mutante: Nº34</li>
</ul>

<h4>Runeconsultas: Nº9, Nº11, Nº14, Nº15, Nº17, Nº18, Nº20, Nº21, Nº50, Nº52, Nº60</h4>

<h4>Sangrar por sangrar: Nº53</h4>

<h4>Silencio... ¡Se juega!</h4>
<ul>
    <li>AD&D segunda edición: Nº11</li>
    <li>Advanced squad leader: Nº3</li>
    <li>Aegian strike: Nº8</li>
    <li>Airpower Nº34</li>
    <li>Battletech: Juego de guerra mecanizada: Nº29</li>
    <li>Blackbeard: Nº40</li>
    <li>Business strategy: Nº16</li>
    <li>Britannia: Nº5</li>
    <li>Capturad su estandarte: Nº30</li>
    <li>Central America: Nº7</li>
    <li>Civilización, el clásico de los clásicos: Nº45</li>
    <li>Cruzada estelar: Nº41</li>
    <li>Cry Havoc (exp.: el castillo templario): Nº12</li>
    <li>Desde Rusia con Hexágonos: Nº25</li>
    <li>Dune: Nº11</li>
    <li>El duelo (sup. de Dune) Nº11</li>
    <li>El terror que vino de las estrellas: Nº10</li>
    <li>Firepower: Nº5</li>
    <li>Fire in the East: Nº10</li>
    <li>Football strategy: Nº6</li>
    <li>Golpe: Nº31</li>
    <li>Harpoon: Nº20</li>
    <li>History of the world, a vueltas con el mundo: Nº46</li>
    <li>Hitler's war: Nº5</li>
    <li>James Bond: Nº1</li>
    <li>Julio Cesar: Nº4</li>
    <li>Kingmaker, la joya de la corona: Nº38</li>
    <li>Kursk, la mayor batalla de carros: Nº37</li>
    <li>La batalla del Ebro. Batallas de la guerra civil española, vol. 1: Nº58</li>
    <li>La cosecha de especia (sup. de Dune) Nº11</li>
    <li>La isla de los Grifos: Nº12</li>
    <li>La llamada de Cthulhu: Nº7</li>
    <li>Los hongos de Yuggoth: Nº12</li>
    <li>Machiavelli: Nº10</li>
    <li>Machiavelli. Diplomacia a la italiana, de nuevo. Machiavelli, 2ª edición: Nº56</li>
    <li>MBT: Nº24, Nº27</li>
    <li>Middle earth role playing: Nº3, Nº5</li>
    <li>Napoleon's last battles (Variantes): Nº2</li>
    <li>New world, o jugando al quinto centenario: Nº28</li>
    <li>Omaha beachhead: Nº4</li>
    <li>Operation Cannibal (Burma 1942-1943): Nº61</li>
    <li>Pacific war: Nº3</li>
    <li>Panzerkrieg: Nº9</li>
    <li>Quadrivium, ¿un nuevo concepto de juego? Nº47</li>
    <li>Quinta flota: Nº21</li>
    <li>Platoon revisited: Nº4</li>
    <li>Reino mágico: Nº21</li>
    <li>Runequest: Nº3, Nº7</li>
    <li>Runequest avanzado: Nº10</li>
    <li>Russian campaign por correo: Nº12</li>
    <li>Space hulk: Nº19</li>
    <li>Scorched earth: Nº10</li>
    <li>Second fleet: Nº2</li>
    <li>The civil war: Nº2</li>
    <li>The russian campaign: Nº9</li>
    <li>The political game: Nº3</li>
    <li>Third world war: Nº16</li>
    <li>Thunder at Cassino: Nº7, Nº16</li>
    <li>¿Todavía no has jugado al ASL? Nº26</li>
    <li>Turning point: Stalingrad: Nº18</li>
    <li>Tokyo express: Nº10</li>
    <li>Wargames sobre las cruzadas: Nº59</li>
    <li>Warhammer: Nº6</li>
    <li>Warhammer 40k: Nº20</li>
    <li>Wrassling: Nº22</li>
</ul>

<h4>Tira cómica</h4>
<ul>
    <li>Astar Guars: Nº16</li>
    <li>El club: Nº51, Nº52, Nº53, Nº54, Nº55, Nº56, Nº57, Nº58, Nº59, Nº60, Nº61, Nº62</li>
    <li>El tío trasgo</li>
    <li>50 números y todavía no se aclaran..: Nº50</li>
    <li>¡A la taberna! Nº43</li>
    <li>¡Bautizos complejos! Nº46</li>
    <li>¡Cartas! Nº49</li>
    <li>¿Ciberqué? Nº28</li>
    <li>Complementos: Nº29</li>
    <li>Dime cual es tu miniatura y te diré quien eres: Nº40</li>
    <li>¿Dónde está trasgo? Nº47</li>
    <li>Felices sueños: Nº42</li>
    <li>Héroes y villanos: Nº18</li>
    <li>Horror: Nº37</li>
    <li>Interferencias: Nº39</li>
    <li>La creación de personajes: Nº35</li>
    <li>La pregunta más difícil del universo: Nº36</li>
    <li>La vida no es un juego de rol, baby: Nº19</li>
    <li>¿Master, eres imparcial? Nº38</li>
    <li>Masters inexpertos: Nº17</li>
    <li>Monstruos compendium XXXV: Nº20</li>
    <li>¡Música maestro! Nº48</li>
    <li>Novedades y más novedades: Nº45</li>
    <li>Pifiosos: Nº32</li>
    <li>Pthulhu ha vuelto: Nº30, Nº31, Nº32, Nº33, Nº34</li>
    <li>Question de estilo: Nº22</li>
    <li>Sed cuidadosos, tíos! Nº21</li>
    <li>¡¡Trampas!! Nº44</li>
    <li>Vidas ejemplares: Adolfo Ulez: Nº41</li>
    <li>El tío Napo: Nº23, Nº24, Nº25, Nº26, Nº27</li>
    <li>James Bond: Nº17</li>
    <li>Traveller: Nº15</li>
</ul>

<h3>ARTÍCULOS DE JUEGOS DE ROL Y MONOGRÁFICOS</h3>

<h4>AD&D</h4>
<ul>
    <li>¿Runequest contra Dungeon and dragons? Nº7</li>
    <li>¿Dungeon and dragons contra Fumbler dwarf? Nº7</li>
</ul>

<h4>Analaya, tormenta de arena: Nº38</h4>

<h4>Aquelarre</h4>
<ul>
    <li>Aquelarre en Euzkadi: Nº27</li>
    <li>Danza macabra: Nº30</li>
    <li>Juego de rol demoníaco-mediaval: Nº20</li>
    <li>Rerum demoni: Nº28</li>
    <li>Rinascita, el renacer de Aquelarre: Nº35</li>
</ul>

<h4>Ars magica. El arte de narrar historias: Nº16</h4>

<h4>ASL: Nº4</h4>

<h4>Bitume (asfalto): Nº39</h4>

<h4>Cthulhu en España: Nº53</h4>

<h4>Cruces, ajos y estacas: Nº57</h4>
<ul>
    <li>Vampiros: un mito universal</li>
    <li>Literatura sanguínea</li>
    <li>Palomitas con Ketchup: el vampiro en el cine</li>
    <li>Vlad III, el empalador</li>
</ul>

<h4>Cruzadas en tierra santa: Nº59</h4>
<ul>
    <li>La lucha por tierra santa</li>
    <li>Las invasiones de los frany</li>
    <li>Tierra santa</li>
    <li>Los asesinos</li>
    <li>Imaginería religiosa</li>
</ul>

<h4>Dracs, de brujería a bruixería: Nº40</h4>

<h4>Dragones y mazmorras: Nº29</h4>

<h4>Dicemaster, la revolución de los dados: Nº58</h4>

<h4>Diplomáticos: Nº2, Nº22</h4>

<h4>Diseño de juegos: Nº33</h4>

<h4>D&D</h4>
<ul>
    <li>El origen del juego de rol: Nº29</li>
    <li>Reglas avanzadas de D&D. Guadad el diccionario: Nº29</li>
    <li>Ya están aquí... ¡Bienvenidos! Nº29</li>
</ul>

<h4>El estado de la afición... en Argentina: Nº61</h4>

<h4>El fenómeno ovni: Nº58</h4>
<ul>
    <li>El fenómeno ovni</li>
    <li>El gobierno secreto. Los hombres de negro detrás del poder</li>
    <li>Invasiones literarias</li>
    <li>Mamá, hay un alienígena en mi sopa</li>
    <li>¿Hay alguien ahí?</li>
</ul>

<h4>El príncipe valiente. El juego narrativo: Nº17</h4>

<h4>El rol (inocente) bajo sospecha: Nº42, Nº58</h4>

<h4>El salvaje oeste: Nº61</h4>
<ul>
    <li>El western</li>
    <li>Preguntas y respuestas sobre el verdadero salvaje oeste</li>
</ul>

<h4>El señor de los anillos: Nº13</h4>
<ul>
    <li>El concilio se divierte: Nº15</li>
    <li>El señor de los anillos: Nº12</li>
    <li>Juego de aventuras básico: Nº28</li>
    <li>Juego de rol de la tierra media: Nº28</li>
    <li>Las estancias de los herreros elfos y Lórien: Nº17</li>
    <li>Los asesinos de Dol Amroth y Las puertas de Mordor: Nº16</li>
    <li>Las ruinas malditas de los dunlendinos y Los piratas de Pelargir: Nº18</li>
    <li>Los jinetes de Rohan: Nº20</li>
    <li>Rolemaster: Nº28</li>
</ul>

<h4>Especial Magic, el encuentro. Edición especial Magic</h4>
<ul>
    <li>Magic: Un nuevo hijo en la familia</li>
    <li>Magic: El encuentro</li>
    <li>Reglas de campeonato</li>
    <li>Checklist</li>
    <li>Primeros pasos de un hechicero en Dominia</li>
    <li>Directriz de baraja</li>
    <li>Cambios para pardillos</li>
</ul>

<h4>Especial módulos: Nº48</h4>

<h4>Figuras de plomo: Nº8</h4>

<h4>Flat top: Nº5</h4>

<h4>Fútbol americano: Nº25</h4>

<h4>Frente del Este: Nº9, Nº10</h4>

<h4>James Bond: Nº17, Nº38</h4>

<h4>Juegos de aviación: Nº12</h4>

<h4>Juegos de horror</h4>
<ul>
    <li>Contra el mal: Nº37</li>
    <li>Chill, perpetuo escalofrío: Nº37</li>
    <li>El horror eres tú: Nº37</li>
    <li>El miedo y el rol: Nº46</li>
    <li>El terror está en el aire: Nº37</li>
    <li>Gurps Horror: Nº46</li>
    <li>Horror en cinemascope: Nº37</li>
    <li>Jugar con el miedo: Nº37</li>
    <li>Kult, la muerte es sólo el principio: Nº46</li>
    <li>Malefices, el juego de rol que huele a azufre..: Nº37</li>
    <li>Más miedo: Nº46</li>
    <li>Mors ultima ratio... ¿Quién dijo miedo? Nº46</li>
    <li>Nephilim, la guinda del pastel de lo oculto: Nº37</li>
    <li>Ragnarok, el fin de todos los tiempos: Nº37</li>
    <li>Ravenloft: espada, brujería y... terror: Nº46</li>
    <li>Vampiro, la mascarada: Nº37</li>
    <li>Wraith, the oblivion: Nº46</li>
</ul>

<h4>Juegos de iniciación: Nº7, Nº14</h4>

<h4>Juegos de rol en vivo: Nº24</h4>

<h4>Juegos deportivos: Nº15</h4>

<h4>Juegos en solitario. ¿Juegos para robinsones?: Nº1</h4>

<h4>Jugando a la tierra media: Nº28</h4>

<h4>Killer a la italiana: Nº60</h4>

<h4>La caballería medieval: Nº52</h4>
<ul>
    <li>La caballería histórica</li>
    <li>Las órdenes de caballería</li>
    <li>Héroes: Del Cid campeador a Don Quijote de la mancha</li>
</ul>

<h4>La llamada de Cthulhu: Nº3</h4>

<h4>La magia y el rol: Nº56</h4>
<ul>
    <li>El origen de la magia</li>
    <li>Magos, místicos y alquimistas</li>
    <li>La magia en los juegos de rol</li>
    <li>La noche de San Juan, fuego y brujería: Nº41</li>
</ul>

<h4>Las cartas sobre la mesa: Nº44</h4>
<ul>
    <li>Érase una vez</li>
    <li>Lo que se nos viene encima</li>
    <li>Magic: the sensation</li>
    <li>Pero... ¿qué está pasando?</li>
    <li>Rol con cartas, cartas y rol</li>
    <li>Tablero + cartas</li>
    <li>Viejas camaradas</li>
</ul>

<h4>Las flotas: Nº30</h4>

<h4>Locos por el juego: Nº40</h4>

<h4>Mad Max: Nº39</h4>

<h4>Masters de Rol: Nº31</h4>

<h4>Módulos y escenarios: Nº36</h4>

<h4>El señor de los anillos en cartas: Nº50</h4>
<ul>
    <li>El día D</li>
    <li>El mecano de el señor de los anillos</li>
    <li>El retorno del rey</li>
    <li>La tierra media... en tu baraja</li>
    <li>Listado: el señor de los anillos</li>
    <li>Todo lo que usted quiso saber sobre SATM y todavía no ha logrado entender</li>
    <li>Una imagen vale más que... ninguna</li>
</ul>

<h4>Panorama para jugar II: Nº20</h4>

<h4>Paranoia: Nº18</h4>

<h4>Pendragón: Nº32</h4>

<h4>Pintar y coleccionar figuras de plomo: Nº34</h4>

<h4>Prensa lúdica: Nº26</h4>

<h4>Rol a carcajadas: Nº45</h4>
<ul>
    <li>Ases del humor</li>
    <li>Misión: cazar a Morta</li>
    <li>¿Qué hay de nuevo, viejo?</li>
</ul>

<h4>Runequest: Nº6</h4>

<h4>SATM</h4>
<ul>
    <li>La batalla de los campos de Pelennor: Nº51</li>
    <li>Dudas, ruegos y pregunta sobre las cartas y el juego: Nº51</li>
</ul>

<h4>Serie negra: Nº55</h4>
<ul>
    <li>Estados unidos entre guerras (1919-1941)</li>
    <li>Novela negra o el lado oscuro de la realidad</li>
    <li>El cine negro</li>
    <li>Los guardianes de la ley</li>
    <li>El largo brazo de la ley</li>
    <li>Los gangsters</li>
    <li>Los más buscados</li>
</ul>

<h4>Star Trek: Nº51</h4>
<ul>
    <li>Bibliografía</li>
    <li>Star Trek. El fenómeno</li>
    <li>Star Trek. Viaje a su historia</li>
</ul>

<h4>Star Wars</h4>
<ul>
    <li>El camino hacia la luz: Nº35</li>
    <li>En una galaxia muy lejana: Nº47</li>
    <li>Informe sobre la disciplina Jedi: Nº35</li>
    <li>Jedi: el Zen en Star Wars: Nº35</li>
    <li>La galaxia informática: Nº47</li>
    <li>La luz y el lado oscuro de la fuerza: Nº16</li>
    <li>Que el presupuesto te acompañe: Nº16</li>
    <li>Que la imaginación te acompañe: Nº16</li>
    <li>Star Wars, la segunda edición: Nº47</li>
    <li>Star Wars: ¿The next generation?: Nº47</li>
    <li>¿Y después del Jedi, qué? Nº47</li>
</ul>

<h4>Stormbringer: Nº19</h4>

<h4>Superhérores del rol: Nº43</h4>
<ul>
    <li>Champions</li>
    <li>DC Heroes, el espíritu de los comics</li>
    <li>El comic de Superhéroes</li>
    <li>In nomine Satanis/Magna veritas</li>
    <li>Jugando en superlativo</li>
    <li>Judge Dredd, el juego de rol</li>
    <li>Marvel Super heroes</li>
    <li>Qué nos dejamos en el tintero (juegos de superhéroes)</li>
    <li>Tortugas fuera del acuario</li>
    <li>Una sombra en la noche</li>
</ul>

<h4>Tac air: Nº21</h4>

<h4>Traveller y Megatraveller: Nº23</h4>

<h4>Un futuro muy sombrío: Nº49</h4>
<ul>
    <li>De la ciencia ficción "hard" al "cyberpunk"</li>
    <li>Los Angeles, noviembre 2019</li>
    <li>Más cyberpunk para jugar</li>
    <li>Que es eso a lo que llamamos cyberpunk</li>
    <li>Tecnología en el papel</li>
</ul>
<h4>Wargames napoleónicos: Nº11</h4>

<h3>JUEGOS DE ROL COMPLETOS</h3>
<ul>
    <li>MILI KK: Nº33</li>
    <li>¡Niños!, el juego de rol de los niños de goma: Nº45</li>
    <li>Star Trek: Nº51</li>
    <li>Traveller. Juego básico y pantallas</li>
</ul>

<h3>ARTÍCULOS GENÉRICOS</h3>

<h4>50º aniversario de la batalla de Kursk: Nº37</h4>

<h4>Abstracción y simulación: Nº46</h4>

<h4>Algo de vikingos: Nº26</h4>

<h4>Asfalto caliente: Nº39</h4>

<h4>Blood bowl, una sangrienta parodia: Nº25</h4>

<h4>Cañoneando en el desierto. Una aventura al Oeste del Alamein: Nº26</h4>

<h4>Censo de clubs: Nº40</h4>

<h4>Comandos de guerra. El juego de rol de la segunda guerra mundial: Nº47</h4>

<h4>Comentarios de un diseñador de juegos: Nº39</h4>

<h4>Cuando la realidad supera a la ficción. (Primera guerra del golfo): Nº22</h4>

<h4>Cyberpunk</h4>
<ul>
    <li>Cyberpunk, edición española: Nº49</li>
    <li>Esta ciudad es un sitio peligroso: Nº31</li>
</ul>

<h4>Dark future: Nº39</h4>

<h4>DC Heroes. El juego: Nº16</h4>

<h4>De la afición a la profesión: Nº40</h4>

<h4>De la caliente arena a la fría nieve: Nº44</h4>

<h4>Detrás del emperador: Nº49</h4>

<h4>Día de Joc y jornadas</h4>
<ul>
    <li>8º salón de juegos, París 1993: Nº35</li>
    <li>16º Campeonato del mundo de Othello: Nº32</li>
    <li>¿Alguien sabe algo de la JESYR? Nº28</li>
    <li>Calentando los dados: Nº44, Nº45, Nº46, Nº51, Nº52</li>
    <li>Conque '96. Roleando con Moctezuma: Nº55</li>
    <li>Día de Joc: Nº39</li>
    <li>Día de Joc '95: Nº47</li>
    <li>Día de Joc '96: Nº53</li>
    <li>Día de Joc '97: Nº58, Nº59</li>
    <li>Día de juego: Nº55</li>
    <li>Día de juego en Madrid: un buen intento: Nº61</li>
    <li>Ecos de la Jesyr 91: Nº23</li>
    <li>Ecos de los días de Joc (especial día de Joc): Nº41</li>
    <li>Enjusim 91: Nº24</li>
    <li>Gen con '94: Nº45</li>
    <li>Gen con '95. Rol en acció: Nº50</li>
    <li>Golferichs. Un buen ejemplo: Nº30</li>
    <li>I semana mediaval de Ancs: Nº55</li>
    <li>Jornadas de estrategia, simulación y rol CON 91: Nº27</li>
    <li>Jugar, jugar, jugar: Nº41</li>
    <li>L'annex de Golferix: Un sitio para jugar: Nº16</li>
    <li>Las Gen con: Ice age: Nº57</li>
    <li>¿Qué pasa con las JESYR? Nº20</li>
</ul>

<h4>Diplomacia: Nº45</h4>

<h4>El mago: Nº56</h4>

<h4>El rol tiene mala prensa: Nº42</h4>

<h4>Entrevistas</h4>
<ul>
    <li>Al habla con... Jordi Zamarreño: Nº2</li>
    <li>Entrevista con Didier "Casus" Guiserix: Nº43</li>
    <li>Entrevista a Francesc Matas: Nº45, Nº50</li>
    <li>Entrevista con Ferran Arbós: Nº40</li>
    <li>Entrevista con Pete Fenlon: Nº54</li>
    <li>Gary Gygax, entrevista al gran culpable: Nº36</li>
    <li>Invocando al innombrable: Nº44</li>
    <li>Los padre de Arturo: Nº39</li>
    <li>Steve Jackson en Barcelona: Nº25</li>
</ul>

<h4>Fanhunter. Ese juego: Nº45</h4>

<h4>Fleet. Evolucionar o morir: Nº30</h4>

<h4>Fuerza Delta, un nuevo juego de rol: Nº27</h4>

<h4>Fumbler dwarf. ¿Dungeon and dragons contra Fumbler dwarf? Nº7</h4>

<h4>Genéricos</h4>
<ul>
    <li>El rol en ciencia ficción: Nº16</li>
    <li>Los siete roles malditos: Nº20</li>
    <li>¡Oh ruooolo mío! El juego de rol en Italia: Nº33</li>
</ul>

<h4>Imperium romanum: Nº14</h4>

<h4>James Bond</h4>
<ul>
    <li>007. El juego de rol: Nº17</li>
    <li>007. Historia de un héroe: Nº17</li>
    <li>Carta del mayor Geoffrey Boothroyd "Q" a la redacción de..: Nº10</li>
    <li>¿Es aquí donde se ha pedido un héroe?: Nº4</li>
    <li>James Bond. El juego de la seducción: Nº17</li>
    <li>La experiencia, madre de la supervivencia: Nº17</li>
    <li>¿Y Bond? ¿Donde está James Bond? Nº17</li>
</ul>

<h4>JRR Tolkien. ¿Un homenaje? Nº28</h4>

<h4>Juegos de cartas</h4>
<ul>
    <li>El día que se hundió Magik: Nº48</li>
    <li>El señor de los Anillos. Juego de cartas coleccionable de la Tierra Media: Nº49</li>
    <li>La ira del Dragón: Nº48</li>
    <li>Magic. La 4ª edición: Nº48</li>
    <li>Magic. Las dudas: Nº47</li>
    <li>Marvel overpower. El juego de cartas de los superhéroes de marvel: Nº50</li>
    <li>Re Cuor di Leone, la Spaghetti-Card: Nº47</li>
    <li>The great Dalmuti. Juego de cartas no coleccionable: Nº50</li>
    <li>Wargames en cartas: la mejor defensa es un buen ataque: Nº49</li>
</ul>

<h4>La llamada de Cthulhu</h4>
<ul>
    <li>Carta de Greg Stafford: Nº4</li>
    <li>Cthulhu había llegado: Nº19</li>
    <li>La maldición de los Chthonians: Nº14</li>
</ul>

<h4>La noche mágica: Nº41</h4>

<h4>La noche más larga: Nº41</h4>

<h4>La revista y el juego de rol nacional: Nº40</h4>

<h4>La table ronde: Nº32</h4>

<h4>Las brujas según las brujas: Nº41</h4>

<h4>Legaliza tu club de rol: Nº40</h4>

<h4>Locos por el juego: Nº40</h4>

<h4>Los asesinos del juego de rol: Nº42</h4>

<h4>Los cazafantasmas: Nº29</h4>

<h4>Los jinetes del asfalto: Nº39</h4>

<h4>Madrid, en el ojo del huracán: Nº42</h4>

<h4>Mirándonos el ombligo: Nº29</h4>

<h4>MBT: Nº14</h4>

<h4>Mutantes en la sombra: Nº24</h4>

<h4>Oráculo</h4>
<ul>
    <li>Oráculo, el juego de los clásicos: Nº32</li>
    <li>Todavía hay juegos por inventar: Nº31</li>
</ul>

<h4>Paranoia</h4>
<ul>
    <li>El juego de rol: Nº14</li>
    <li>El mundo de paranoia: Nº18</li>
    <li>Previsión de publicaciones en castellano: Nº18</li>
</ul>

<h4>Pegando unos tiros. Paintball en España: Nº34</h4>

<h4>Pendragon</h4>
<ul>
    <li>El rey arturo Pendragon. Artículo sobre el juego de rol: Nº32</li>
    <li>El rey que fue y será: Nº32</li>
</ul>

<h4>Pesquisas británicas: Nº57</h4>

<h4>Principe valiente: Nº32</h4>

<h4>Prensa lúdica. Las revistas de juegos fuera de nuestras fronteras: Nº26</h4>

<h4>¿Qué pasa en las ondas? Nº38</h4>

<h4>Road Hogs, Marranos de carretera: Nº39</h4>

<h4>Rol en vivo</h4>
<ul>
    <li>Es solo un juego pero me gusta: Nº24</li>
    <li>Killer: Del asesinato considerado como una de las Bellas artes: Nº24</li>
    <li>La esperanza del Talismán: Nº24</li>
    <li>Un nuevo enfoque de las actividades al aire libre: Nº24</li>
</ul>

<h4>Repóquer de flotas: Nº30</h4>

<h4>Runequest</h4>
<ul>
    <li>Applelane, el suplemento: Nº17</li>
    <li>Concurso: Nº26</li>
    <li>Dioses de Glorantha: Nº14</li>
    <li>Glorantha: Nº18</li>
    <li>Greg Stafford. Entrevista con el padre de Glorantha: Nº33</li>
    <li>Concurso RQ básico: Nº33</li>
    <li>No es fácil ser un pato en Glorantha: Nº6</li>
    <li>¿Runequest contra Dungeon and dragons? Nº7</li>
    <li>Runemagia: Nº6</li>
    <li>Un elfo y su fe: Nº6</li>
</ul>

<h4>Si aquello es una bandera negra me temo que estamos en el Caribe: Nº40</h4>

<h4>Shell Shock! Nº26</h4>

<h4>Shadowrun: la alternativa: Nº49</h4>

<h4>Solo para sus ojos: Nº38</h4>

<h4>Stormbringer</h4>
<ul>
    <li>Canto infernal: Nº24</li>
    <li>Crónicas de la espada negra: Nº17</li>
    <li>El juego de rol en los mundos de Michael Moorcock: Nº16</li>
    <li>El juego de rol en los reinos jóvenes de Elric: Nº19</li>
    <li>Esto es lo que hay: Nº19</li>
    <li>Eterna lucha entre caos y bien: Nº15</li>
    <li>Solo apto para los más duros: Nº28</li>
</ul>

<h4>Touchdown</h4>
<ul>
    <li>Erratas del número 25: Nº26</li>
    <li>Fútbol americano por correo: Nº25</li>
    <li>Juego gratuito: Nº25</li>
</ul>

<h4>Traveller</h4>
<ul>
    <li>Introducción a Traveller: Nº23</li>
    <li>Feliz 10 aniversario: Nº2</li>
</ul>

<h4>Última copa. Carta abierta de despedida: Nº47</h4>

<h4>Un fenómeno universal: Nº41</h4>

<h4>Vampiro, la mascarada: Nº37</h4>

<h3>ESCENARIOS Y AYUDAS PARA WARGAMES</h3>

<h4>Airforce one. Achtung! Dicke autos! Nº12</h4>

<h4>Air power. Intruder: Nº34</h4>

<h4>Ars Magica. Rectificación de el Jinete de la tormenta: Nº42</h4>

<h4>ASL</h4>
<ul>
    <li>Apenas nos hablamos: Nº26</li>
    <li>Belchite '37: Nº36</li>
    <li>La estación de Suhinicio: Nº4</li>
    <li>Nuts: Nº54</li>
</ul>

<h4>B-17. Variantes: Nº15</h4>

<h4>Battletech</h4>
<ul>
    <li>Al asalto: Nº29</li>
    <li>Combate callejero: Nº36</li>
    <li>Metal contra escamas: Nº42</li>
</ul>

<h4>Britannia. Preguntas y respuestas: Nº5</h4>

<h4>Car Wars. A todo esto, ¿dónde están los arcos?</h4>

<h4>Civilización. Avanzado. Más allá de la décimo primera carta: Nº18</h4>

<h4>Cruzada estelar. Misión 547/14 - Sector 37: Nº42</h4>

<h4>Cry havoc</h4>
<ul>
    <li>Empezamos por el principio: El reparto infructuoso: Nº36</li>
    <li>Los siete magníficos: Nº52</li>
    <li>Robin Hood: Nº14</li>
</ul>

<h4>D-Day. Variantes: Nº14</h4>

<h4>DBM</h4>
<ul>
    <li>La batalla de Tell Basher (Turbessel): Nº59</li>
    <li>Nicópolis, la última cruzada: Nº62</li>
</ul>

<h4>Darkblades. Invasión: Nº32</h4>

<h4>Fantasy Warriors. El puente sobre el río Thil: Nº40</h4>

<h4>Firepower</h4>
<ul>
    <li>Fe de erratas del nº 5: Nº6</li>
    <li>Malvinas, operación "top malo": Nº5</li>
    <li>Objetivo Kolwezi: Nº5</li>
</ul>

<h4>Fite. Udarnaya ukrainia: Nº10</h4>

<h4>Flat top</h4>
<ul>
    <li>Escenario de Leyte hipotético: Nº5</li>
    <li>Reglas para Flat top con árbitro: Nº5</li>
</ul>

<h4>Fleet</h4>
<ul>
    <li>El sueño de Gorshkov. Orden de batalla soviético: Nº30</li>
    <li>Erratas: Nº31</li>
    <li>Ganando barlovento. Orden de batalla español: Nº30</li>
    <li>Levando anclas. Orden de batalla norteamericano: Nº30</li>
</ul>

<h4>Fligh leader. Vocabulario: Nº6</h4>

<h4>Imperium romanum</h4>
<ul>
    <li>La jihad: Nº19</li>
    <li>Nuevas reglas y escenarios: Nº14</li>
</ul>

<h4>MBT</h4>
<ul>
    <li>Fe de erratas de Nisab (Nº 24): Nº26</li>
    <li>Necesitamos un cuartel: Nº25</li>
    <li>Nisab: Nº24</li>
    <li>Tormenta roja sobre Islandia: Nº14</li>
</ul>

<h4>Pelotón. Nuevos escenarios: Nº57</h4>

<h4>SE. Udarnaya ukrainia: Nº10</h4>

<h4>Tac air: Nº21</h4>

<h4>Third reich</h4>
<ul>
    <li>Las esperanzas del eje sur: Nº20</li>
    <li>Las esperanzas del eje sur II: Nº21</li>
    <li>Las esperanzas del eje del sur III y IV: Nº22</li>
    <li>Lucha por el poder en el mediterráneo IV: Nº23</li>
    <li>Lucha por el poder en el mediterráneo V: Nº24</li>
</ul>

<h4>Turning point Stalingrad. Para jugar en solitario: Nº20</h4>

<h4>Third reich</h4>
<ul>
    <li>Conflictos locales y limitados: Nº15</li>
    <li>Nuevas variantes: Nº13</li>
</ul>

<h4>Thunder at Cassino. Atrincherándose: Nº16</h4>

<h4>Vinking's raiders. Invasión: Nº32</h4>

<h4>War and peace. Waterloo: Nº13</h4>

<h4>Warhammer 40k. El ojo del huracán: Nº30</h4>

<h3>AYUDAS PARA ROL</h3>

<h4>AD&D</h4>
<ul>
    <li>1ª y 2ª edición. Pasar de un universo a otro: Nº29</li>
    <li>Conjuros para druidas: Nº4</li>
    <li>Introducción al Berserkr: Nº6</li>
    <li>Los druidas: Nº2</li>
    <li>Los asesinos: Nº1</li>
</ul>

<h4>Aquelarre</h4>
<ul>
    <li>Almogávar, nuevo personaje: Nº20</li>
    <li>Bestiario: Nº27</li>
    <li>Componentes mágicos: Nº22</li>
    <li>Conjuros, mitos y leyendas del País Vasco: Nº27</li>
    <li>El brujo, nueva profesión para Aquelarre: Nº38</li>
    <li>El cabalista, nuevo PJ para aquelarre: Nº56</li>
    <li>El sistema monetario en tiempos de Aquelarre: Nº23</li>
    <li>Fauna ibérica: Nº44</li>
    <li>La cábala: Nº56</li>
    <li>La caballería en la españa mediaval: el infanzón: Nº52,</li>
    <li>Mari o la dama de Amboto: Nº27</li>
    <li>Nobleza catalana (Dracs): Nº40</li>
    <li>Nueva clase de personaje no oficial para Aquelarre: el asesino: Nº59</li>
    <li>Prostituta y pastor: Nuevas profesiones para Aquelarre: Nº29</li>
    <li>Reglas de asedio para Aquelarre: Nº25</li>
</ul>

<h4>Coca de San Juan. Para cocinar: Nº41</h4>

<h4>Deadlands: Tierras muertas</h4>
<ul>
    <li>Abilene: Nº61</li>
</ul>

<h4>El señor de los anillos</h4>
<ul>
    <li>La semana de los juegos: Nº52,</li>
    <li>Rynd Aratoran: La orden de los paladines: Nº62</li>
    <li>Trasgos y grandes trasgos: Nº28</li>
</ul>

<h4>Elric</h4>
<ul>
    <li>Mandressla: Nº62</li>
</ul>

<h4>Far West</h4>
<ul>
    <li>Las ciudades ganaderas: Nº61</li>
</ul>

<h4>Genéricos</h4>
<ul>
    <li>Algunas reglas para movimiento estratégico en wargames: Nº8</li>
    <li>Aventúrate pero seguro (tratado de supervivencia en dungeons): Nº2</li>
    <li>Bestiario: Los pelotas: Nº3</li>
    <li>Biografías (de España de principios del S. XX): Nº53</li>
    <li>Costumbres sociales en la Edad Media: Nº24</li>
    <li>Cuasi alineamientos para jugadores: Nº3</li>
    <li>El miedo y el rol: Nº46</li>
    <li>España, 1918-1931: Nº53</li>
    <li>Historia y organización de las fuerzas aéreas japonesas en la II guerra mundial: Nº12</li>
    <li>In memoriam (cosas extrañas en la España de principios del S. XX): Nº53</li>
    <li>La música y el rol: Nº16</li>
    <li>La tabla definitiva: Nº31</li>
    <li>Los puñales: Nº26</li>
    <li>Los siete mandamientos del Master marchoso y con salero: Nº32</li>
    <li>Masters de rol: papel de estrella: Nº31</li>
    <li>Momentos y lugares: Nº41</li>
    <li>Nombres aragoneses: Nº23</li>
    <li>¿Nos vamos de copas? (Generador de nombres de tabernas): Nº24</li>
    <li>Palabra de Master: Nº31</li>
    <li>Precio y dinero (España 1918-1931): Nº53</li>
    <li>¿Qué es el juego de rol? Nº31</li>
    <li>Reglas de navegación para un universo mediaval: Nº31</li>
    <li>Sistema de magia universal: Nº56</li>
    <li>Sociedades secretas en los años 20: Nº53</li>
    <li>Un día en la España de Alfonso XIII: Nº53</li>
    <li>Últimas palabras (de los PJs): Nº4</li>
    <li>Wargames. Reglas y sugerencias para tiempo atmosférico para guerras modernas: Nº14</li>
</ul>

<h4>GURPS. Generación de personajes que vivieron la gran guerra: Nº29</h4>

<h4>In nomine Satanis/Magna veritas. Visualización de daños en INS/MV: Nº47</h4>

<h4>James Bond</h4>
<ul>
    <li>007: Equipo de la rama Q: Nº17</li>
    <li>Aclaraciones sobre el combate: Nº17</li>
    <li>Idiomas en el James Bond 007: Nº21</li>
    <li>Nuevas armas para los agentes M.I. 6: Nº38</li>
    <li>Nuevo equipo Q para agentes M. I. 6: Nº38</li>
    <li>Reflexiones sobre el mundo de J.B. después de la caída del bloque comunista: Nº34</li>
    <li>Sobre cuatro ruedas: Nº38</li>
</ul>

<h4>Kult. Los padres de la ciudad: Nº53</h4>

<h4>La llamada de Cthulhu</h4>
<ul>
    <li>Algo sobre las profesiones de La llamada de Cthulhu: Nº16</li>
    <li>Armas flexibles: Nº12</li>
    <li>Calentando motores: Nº6</li>
    <li>Consejos para los guardianes: Nº11</li>
    <li>Cthulhu airlines: Nº12</li>
    <li>Cthulhu armería: Nº3</li>
    <li>Cthulhu by gaslight: Nº3</li>
    <li>Cthulhu ponte guapo: Nº3</li>
    <li>Cthulhu locura: Nº3</li>
    <li>El master siempre es culpable: Nº9</li>
    <li>El vampiro en la llamada de Cthulhu: Nº21</li>
    <li>Hace pum: Nº16</li>
    <li>La ley de los ángeles descarnados de la noche: Nº32</li>
    <li>Los libros del horror: Nº37, Nº38(Bajo el efecto de la maldición. Fe de erratas de los libros del horror)</li>
    <li>Los que acechan en la oscuridad (fantasmas): Nº11</li>
    <li>Más habilidades: Nº30</li>
    <li>Nivel de vida: una alternativa a la habilidad de crédito: Nº39</li>
    <li>(Nueva) tabla de fobias para (jugadores de) La llamada de Cthulhu: Nº9</li>
    <li>Otra forma de crear el investigador en los mitos: Nº3</li>
    <li>Otro método de creación de personajes: Nº11</li>
    <li>Premios para Cthulhu (para jugadore de Cthulhu): Nº3</li>
    <li>Psicología en la llamada de Cthulhu (I): Nº25</li>
    <li>Psicología en la llamada de Cthulhu (II): Nº27</li>
    <li>Rotheps. Pirañas del lago Hali (raza servidora menor): Nº26</li>
    <li>Siga a ese coche: Nº14</li>
    <li>Sistema de investigación: Nº62</li>
    <li>Solo contra el Wendigo. Fe de erratas: Nº10</li>
    <li>Un ejemplo de Cthulhu en directo: Nº3</li>
    <li>Verdun fue peor: Nº29</li>
</ul>

<h4>Mutantes en la sombra</h4>
<ul>
    <li>Erratas: Nº27</li>
    <li>Influencia del alcohol en mutantes en la sombra: Nº29</li>
</ul>

<h4>Nephilim</h4>
<ul>
    <li>Sistema de creación familiar: Nº51</li>
</ul>

<h4>Paranoia</h4>
<ul>
    <li>Algunas ideas extra sobre organización de campañas: Nº18</li>
    <li>Inventos del SID: Nº28</li>
    <li>Lexicón: Nº26</li>
</ul>

<h4>Pendragon</h4>
<ul>
    <li>El lenguaje de los blasones: Nº32</li>
</ul>

<h4>Ragnarok</h4>
<ul>
    <li>El estrés en Ragnarok: Nº46</li>
    <li>Reglas para desórdenes sexuales en Ragnarok: Nº41</li>
</ul>

<h4>Rolemaster. La semana de los juegos: Nº52</h4>

<h4>Runequest</h4>
<ul>
    <li>Complementos para Runequest clásico: Nº7</li>
    <li>Consejos para la creación y manejo de shamanes: Nº19</li>
    <li>Fe de erratas: Nº8</li>
    <li>Grimorio: Nº18, Nº19</li>
    <li>Los vikingos: Nº9</li>
    <li>Método deliberado y combinado para crear a personajes no humanos: Nº18</li>
    <li>Modificaciones para un juego casi perfecto: Nº6</li>
</ul>

<h4>Star Trek</h4>
<ul>
    <li>Sistema de combate de naves: Nº62</li>
</ul>

<h4>Star Wars</h4>
<ul>
    <li>Canalización de energía: Nº62</li>
    <li>Dumplie y Psicópata vengador: Nº28</li>
    <li>El lanzallamas. Nueva arma para Star Wars: Nº41</li>
    <li>Libertad en la galaxia: Nº16</li>
    <li>Libertad en la galaxia. 2ª entrega: Nº17</li>
    <li>Libertad en la galaxia. 3ª entrega: Nº18</li>
    <li>Nuevas razas: Nº20</li>
    <li>Nuevos personajes: Nº30</li>
    <li>Nuevo personaje para Starwars. El desertor imperial: Nº18</li>
    <li>Nuevo personaje para Starwars . El policía: Nº11</li>
    <li>Reglas adicionales para Star Wars: Nº39</li>
    <li>Torpedos en el artículo: La torre de Babel: Nº30</li>
</ul>

<h4>Stormbringer</h4>
<ul>
    <li>Arte y peligro de invocar demonios: Nº19</li>
    <li>El bosque de Troos: Nº45</li>
    <li>El peso de la ley: Nº23</li>
    <li>Los diez profetas negro de Nirhain: Nº43</li>
    <li>Los duques del Caos I: Nº19</li>
    <li>Los duques del Caos II: Nº20</li>
    <li>Los laberintos del multiverso: Nº19</li>
    <li>Mandressla: Nº62</li>
    <li>Nuevo origen social: El artista: Nº19</li>
</ul>

<h4>Traveller-Megatraveller</h4>
<ul>
    <li>1001 personajes</li>
    <li>Científicos en Megatraveller: Nº23</li>
    <li>Kinuir</li>
    <li>Mercenario</li>
</ul>

<h4>Universo</h4>
<ul>
    <li>Expediente X: Nº50</li>
</ul>

<h4>Vampiro, edad oscura</h4>
<ul>
    <li>Al-andalus, una crónica basada en el Tarot: Nº62</li>
</ul>

<h4>Vampiro, la mascarada</h4>
<ul>
    <li>Barcelona by night: Nº46</li>
    <li>Barcelona by night: los secretos: Nº57</li>
</ul>

<h3>MÓDULOS</h3>

<h4>AD&D</h4>
<ul>
    <li>Leurcodnum. Capítulo I: Nº1</li>
    <li>Leurcodnum. Capítulo II: Nº2</li>
    <li>Leurcodnum. Capítulo III: Nº3</li>
    <li>Leurcodnum. Capítulo IV: Nº4</li>
    <li>Leurcodnum. Capítulo V: Nº7</li>
</ul>

<h4>Almogávers</h4>
<ul>
    <li>El retorno del muerto: Nº50</li>
    <li>El tesoro perdido I. De Constantinopla hasta Tiro: Nº59</li>
    <li>El tesoro perdido (segunda parte). Jerusalén y más allá: Nº60</li>
    <li>El tesoro perdido (tercera parte). El templo del mar muerto: Nº61</li>
    <li>La secta del dragón: Nº49</li>
    <li>La senda del lado oscuro: Nº51</li>
</ul>

<h4>Analaya</h4>
<ul>
    <li>Una mujer y un deseo: Nº42</li>
</ul>

<h4>Aquelarre</h4>
<ul>
    <li>Contacto: Nº29</li>
    <li>El compromiso indisoluble: Nº47</li>
    <li>El despertar de la bestia: Nº56</li>
    <li>El regreso: Nº21</li>
    <li>El retorno del muerto: Nº50</li>
    <li>El romance de Diego León: Nº26</li>
    <li>El regreso del señor del Segre: Nº24</li>
    <li>El tesoro perdido I. De Constantinopla hasta Tiro: Nº59</li>
    <li>El tesoro perdido (segunda parte). Jerusalén y más allá: Nº60</li>
    <li>El tesoro perdido (tercera parte). El templo del mar muerto: Nº61</li>
    <li>Intrigas en villa y corte: Nº54</li>
    <li>La secta del dragón: Nº49</li>
    <li>La senda del lado oscuro: Nº51</li>
    <li>La sombra en el espejo: Nº32</li>
    <li>Lágrimas: Nº38</li>
    <li>Los sueños de Ekaitz: Nº27</li>
    <li>Murder party: Nº33</li>
    <li>Nox demoni? Nº41</li>
    <li>Prisionero en Argel: Nº36</li>
</ul>

<h4>Ars mágica</h4>
<ul>
    <li>El lago de las flores: Nº52</li>
</ul>

<h4>Castillo de Falkenstein</h4>
<ul>
    <li>El manto de Laertes: Nº56</li>
</ul>

<h4>Cazafantasmas</h4>
<ul>
    <li>¡A por el niño! Nº45</li>
</ul>

<h4>Comandos de guerra</h4>
<ul>
    <li>La fórmula secreta: Nº60</li>
</ul>

<h4>Cyberpunk</h4>
<ul>
    <li>No sin mi hija: Nº60</li>
    <li>Oveja negra: Nº31</li>
    <li>Un container al rojo vivo: Nº49</li>
</ul>

<h4>D&D</h4>
<ul>
    <li>El ducado de Sparkguard: Nº11</li>
</ul>

<h4>Deadlands: Tierras muertas</h4>
<ul>
    <li>Camino de Abilene: Nº61</li>
</ul>

<h4>El señor de los anillos</h4>
<ul>
    <li>Anórien: Nº28</li>
    <li>El espíritu atormentado: Nº42</li>
    <li>El Silmadûr: Nº13</li>
    <li>El sueño de los Ents: Nº14</li>
    <li>Espías en Mordor: Nº48</li>
    <li>La maldición de Alvoe: Nº20</li>
    <li>Las torres de Zârräsh Dûr: Nº40</li>
    <li>Tharnefuin (A través de la oscuridad): Nº21</li>
    <li>Tharnefuin (cont.): Nº22</li>
    <li>Tharnefuin III: Nº23</li>
    <li>Tharnefuin. IV: Nº24</li>
</ul>

<h4>El príncipe valiente</h4>
<ul>
    <li>La daga de plata: Nº20</li>
</ul>

<h4>Fanhunter</h4>
<ul>
    <li>El caso del zumosor: Nº54
    </li>
    <li>Por fin ya es viernes: Nº42
    </li>
</ul>

<h4>Far West</h4>
<ul>
    <li>El heredero: Nº57
    </li>
    <li>El precio de una amistad: Nº36
    </li>
    <li>Hooka Hey: Nº48
    </li>
    <li>Oro en Piedra Rota: Nº42
    </li>
</ul>

<h4>Genérico</h4>
<ul>
    <li>El muñeco diabólico. Idea para módulo: Nº37
    </li>
    <li>Freddy Krueger. Idea para módulo: Nº37
    </li>
    <li>Ideas para aventura de ambiente medieval: Nº41
    </li>
</ul>

<h4>Hombre lobo</h4>
<ul>
    <li>Criaturas del señor: Nº60
    </li>
</ul>

<h4>INS/MV</h4>
<ul>
    <li>El predicador: Nº51
    </li>
    <li>La vida es como una caja de bombones: Nº58
    </li>
    <li>Te amaré hasta que te mate (casi una historia de amor): Nº46
    </li>
</ul>

<h4>Invasores</h4>
<ul>
    <li>Fargo: Nº58
    </li>
</ul>

<h4>James Bond</h4>
<ul>
    <li>Casino royale: Nº17
    </li>
    <li>Operación fénix: Nº38
    </li>
    <li>Operación rompehielos: Nº31
    </li>
    <li>Operación Sword: Nº48</li>
</ul>

<h4>Killer</h4>
<ul>
    <li>Terminator: Nº32
    </li>
</ul>

<h4>Kult</h4>
<ul>
    <li>Línea roja, última parada I: Nº53
    </li>
    <li>Línea roja, última parada II: Matadero: Nº54
    </li>
</ul>

<h4>La llamada de Cthulhu</h4>
<ul>
    <li>A pedra da serpe: Nº18
    </li>
    <li>Al caer la noche: Nº30
    </li>
    <li>Amnesia: Nº20
    </li>
    <li>Brighton Rock (Cthulhu by Gaslight): Nº41
    </li>
    <li>Cerradle la puera al viento: Nº11
    </li>
    <li>El geol: Nº52
    </li>
    <li>El signo de la serpiente: Nº11
    </li>
    <li>El tercer hombre: Nº55
    </li>
    <li>Frankestein. Idea para módulo: Nº37
    </li>
    <li>Fin de semana en Bishop house: Nº8
    </li>
    <li>Isla tranquila: Nº42
    </li>
    <li>King's rock: Nº32
    </li>
    <li>La bestia no debe nacer I. Los elegidos de Yog-Sothoth: Nº12
    </li>
    <li>La bestia no debe nacer II. Salvad a los niños: Nº13
    </li>
    <li>La bestia no debe nacer III. La hora de la revelación: Nº14
    </li>
    <li>La bestia no debe nacer IV. La ciudad de los pilares: Nº15
    </li>
    <li>La bestia no debe nacer V. La batalla final: Nº16
    </li>
    <li>La cabaña del Tío Tom: Nº4
    </li>
    <li>La casa Watson: Nº25
    </li>
    <li>La cruz en llamas: Nº39
    </li>
    <li>La cruz en llamas (y II): Nº40
    </li>
    <li>La desaparición de Linda Warren: Nº6
    </li>
    <li>La expedición Byford: Nº49
    </li>
    <li>La gata de Jade: Nº60
    </li>
    <li>La isla de la Paz: Nº10
    </li>
    <li>Los cazalibros: Nº7
    </li>
    <li>Los huérfanos (Hijos de alguien sin nombre): Nº21
    </li>
    <li>Memorias de África: Nº54
    </li>
    <li>Muerte en el expreso: Nº9
    </li>
    <li>Sombras y niebla: Nº57
    </li>
    <li>Tras tus pasos: Nº35
    </li>
</ul>

<h4>Mili KK</h4>
<ul>
    <li>Desmadre sexual de una noche de verano: Nº43
    </li>
    <li>Un puente lejano: Nº36
    </li>
    <li>Suvervivencia: Nº33
    </li>
</ul>

<h4>Mutantes en la sombra</h4>
<ul>
    <li>Boeing 747: Nº44
    </li>
</ul>

<h4>Nephilim</h4>
<ul>
    <li>El nombre de la rosa: Nº47</li>
</ul>

<h4>¡Niños!</h4>
<ul>
    <li>Dos granujas de cuidado: Nº45
    </li>
    <li>El secuestro: Nº48
    </li>
</ul>

<h4>Oráculo</h4>
<ul>
    <li>El rapto de Egea: Nº36
    </li>
    <li>Limpieza étnica: Nº42
    </li>
    <li>Limpieza étnica (II): Nº43
    </li>
    <li>Némesis: Nº34
    </li>
</ul>

<h4>Paranoia</h4>
<ul>
    <li>Billetes por favor: Nº32
    </li>
    <li>Cazarobots II: Misión gloriosa: Nº39
    </li>
    <li>El anillo comunista: Nº42
    </li>
    <li>Golpe en la pequeña URS: Nº27
    </li>
    <li>Los cuentos del abuelo ordenador. Caperucita-R-OJA: Nº48
    </li>
    <li>Nunca digas nunca jamás, amigo ciudadano: Nº20
    </li>
</ul>

<h4>Pendragón</h4>
<ul>
    <li>Aventura de la dama difamada
    </li>
    <li>Aventura del Ciervo blanco
    </li>
    <li>Aventura de los dos hermanos
    </li>
</ul>

<h4>Príncipe valiente</h4>
<ul>
    <li>Alas en el mar: Nº26
    </li>
</ul>

<h4>Ragnarok</h4>
<ul>
    <li>La pira de San Joan: Nº41
    </li>
    <li>Leatherface. Idea para módulo: Nº37
    </li>
</ul>

<h4>Rolemaster</h4>
<ul>
    <li>Alrededor del mundo en búsqueda de una canción: Nº36
    </li>
    <li>El retorno de la maldad: Nº15
    </li>
    <li>La espada de Ganaël: Nº58
    </li>
</ul>

<h4>Runequest</h4>
<ul>
    <li>Asuntos de familia I: Nº54
    </li>
    <li>Asuntos de familia II: Nº55
    </li>
    <li>Aventura de Melderyn en Nurisel: Nº10
    </li>
    <li>Bambú y barro: Nº29
    </li>
    <li>Broo: Nº12
    </li>
    <li>El libro de los Dragonewts: Nº5
    </li>
    <li>El sátiro maligno: Nº48
    </li>
    <li>Kerima: Nº13
    </li>
    <li>La casa de Madame Chasternan: Nº30
    </li>
    <li>Ladrones de Elamle: Nº8
    </li>
    <li>La jihad: Nº19
    </li>
    <li>Las armas doradas: Nº7
    </li>
    <li>Las minas de Mindolluin I: Nº9
    </li>
    <li>La minas de Mindolluin II. La necrópolis: Nº11
    </li>
    <li>Las minas de Mindolluin III. Luna roja llena: Nº14
    </li>
    <li>Las minas de Mindolluin IV. Cuarto nivel: Nº15
    </li>
    <li>Las minas de Mindolluin V. Quinto nivel.Nº17
    </li>
    <li>La noche de la muerte: Nº18
    </li>
    <li>Un día en las carreras: Nº20
    </li>
</ul>

<h4>Star Trek</h4>
<ul>
    <li>Donde ningún hombre ha ido jamás: Nº51
    </li>
</ul>

<h4>Star Wars</h4>
<ul>
    <li>Asesinato en Lloor-T: Nº33
    </li>
    <li>Balada gamorreana: Nº26
    </li>
    <li>Cazadores cazados: Nº44
    </li>
    <li>El camino del Jedi: Nº35
    </li>
    <li>El planeta moribundo: Nº47
    </li>
    <li>El viaje del Walkiria: Nº48
    </li>
    <li>Esclavos de ojos tristes: Nº50
    </li>
    <li>Huída de Sarrabahn: Nº59
    </li>
    <li>Los señores del crimen I. Misterio en Mom Gemhar: Nº52,
    </li>
    <li>Los señores del crimen II. Misión diplomática: Nº53
    </li>
    <li>Los señores del crimen III. El encuentro final: Nº54
    </li>
    <li>Misión de exploración: Nº36
    </li>
    <li>Resurrección: Nº34
    </li>
    <li>Schannor: Nº60
    </li>
    <li>Vacaciones en Tatooine: Nº23
    </li>
</ul>

<h4>Stormbringer</h4>
<ul>
    <li>A través del bosque de Troos (I): Nº45
    </li>
    <li>A través del bosque de Troos (II): Nº46
    </li>
    <li>Conjura palatina: Nº24
    </li>
    <li>El último señor de Erael: Nº34
    </li>
    <li>El último señor de Erael: Nº35
    </li>
    <li>La torre: Nº28
    </li>
    <li>Los cantores: Nº22
    </li>
    <li>Sueño eterno: Nº57
    </li>
</ul>

<h4>Superhéroes Inc</h4>
<ul>
    <li>El atrapasueños: Nº55
    </li>
    <li>Misión lunar: Nº61
    </li>
</ul>

<h4>Traveller</h4>
<ul>
    <li>Asunto de comercio: Nº23
    </li>
    <li>El viaje del Walkiria: Nº48
    </li>
</ul>

<h4>Universo</h4>
<ul>
    <li>La verdad está ahí fuera: Nº50
    </li>
</ul>

<h4>Vampiro, la mascarada</h4>
<ul>
    <li>Cambiar de vida: Nº37
    </li>
    <li>Criaturas del señor: Nº60
    </li>
    <li>Hermanos de sangre: Nº48
    </li>
    <li>Licantropunk. Idea para módulo: Nº37
    </li>
    <li>Reservoir bats: Nº54
    </li>
</ul>

<h4>Vampiro: edad oscura</h4>
<ul>
    <li>El veterano de Hattin: Nº59
    </li>
</ul>