<meta charset="UTF-8">
<style>
    article {
        box-shadow: 2px 2px 2px #eee;
        margin: 10px auto;
        max-width: 500px;
        padding: 10px;
    }
    
    h1 {
        /*font-size: 20px;*/
        margin-bottom: 0;
        text-align: center;
    }
    
    h2 {
        font-size: 18px;
    }
    
    section {
        display: flex;
        gap: 80px;
    }
    
    ul {
        font-family: 'Courier New', Courier, monospace;
        padding-left: 22px;
    }
</style>
<article>
    <h1>AVANCES DEL CABALLERO ERRANTE</h1>
    <section>
        <div>
            <h2>NIVEL HABILIDAD</h2>
            <ul>
                <li>Armas marciales c/c</li>
                <li>Armas simples c/c</li>
                <li>Artes militares</li>
                <li>Atletismo</li>
                <li>Disciplina</li>
                <li>Equitación</li>
                <li>Folclore</li>
                <li>Intimidación</li>
                <li>Orientación</li>
                <li>Resistencias</li>
            </ul>
        </div>
        <div>
            <h2>MEJORA BONIFICADOR</h2>
            <ul>
                <li>[BA] Agilidad</li>
                <li>[BF] Físico</li>
                <li>[BF] Físico</li>
                <li>[BC] Combate</li>
                <li>[BC] Combate</li>
                <li>[BI] Inteligencia</li>
                <li>[BV] Voluntad</li>
            </ul>
            <h2>TALENTO</h2>
            <ul>
                <li>Defensa impenetrable</li>
                <li>Golpe brutal</li>
                <li>Monta defensiva</li>
            </ul>
        </div>
    </section>
</article>