
<div class="caja campo">
	<div class="s12 mv15">
		<span class="paper-switch-2-label"><?=t('Borde solo abajo')?></span>
		<label class="paper-switch-2">
			<input <?=empty($caja->borde)?'':'checked'?> type="checkbox" name="borde">
			<span class="paper-switch-slider round"></span>
		</label>
		<span class="paper-switch-2-label"><?=t('A cada lado')?></span>
	</div>

	<div class="s6">
		<label><?=t('Nombre de la variable')?></label>
		<input type="text" name="variable_nombre" value="<?=$caja->variable_nombre?>">
	</div>
	<div class="s6">
		<label><?=t('Valor por defecto')?> <sup><?=t('Opcional')?></sup></label>
		<input type="text" name="variable_valor" value="<?=$caja->variable_valor?>">
	</div>
	<small class="s12"><?=t('El nombre de la variable tiene que ser único y estar compuesto solo por letras sin espacios. Se permite la barra baja para separar palabras. En vez de ñ use "ny".')?></small>
</div>
<input type="hidden" name="tipo" value="campo">
