
<div class="caja campo_de_texto">
	<div class="s12 mv15">
		<span class="paper-switch-2-label"><?=t('Borde solo abajo')?></span>
		<label class="paper-switch-2">
			<input <?=empty($caja->borde)?'':'checked'?> type="checkbox" name="borde">
			<span class="paper-switch-slider round"></span>
		</label>
		<span class="paper-switch-2-label"><?=t('A cada lado')?></span>
	</div>
	
	<?php include APP_PATH . "views/ev/fichas/cajas/elementos/margen_sangria.phtml"; ?>

	<div class="s12">
		<label><?=t('Nombre')?></label>
		<input type="text" name="nombre" value="<?=$caja->nombre?>">
	</div>

	<div class="s12">
		<label><?=t('Notas')?></label>
		<input type="text" name="notas" value="<?=$caja->notas?>">
	</div>
	<div class="s4">
		<label><?=t('Variable')?></label>
		<input type="text" name="variable_nombre" value="<?=$caja->variable_nombre?>">
	</div>
	<div class="s4">
		<label><?=t('Marcador')?> <sup><?=t('Opcional')?></sup></label>
		<input type="text" name="variable_marcador" value="<?=$caja->variable_marcador?>">
	</div>
	<div class="s4">
		<label><?=t('Valor')?> <sup><?=t('Opcional')?></sup></label>
		<input type="text" name="variable_valor" value="<?=$caja->variable_valor?>">
	</div>
	<small class="s12"><?=t('El nombre de la variable tiene que ser único y estar compuesto solo por letras sin espacios. Se permite la barra baja para separar palabras. En vez de ñ use "ny".')?></small>
</div>
<input type="hidden" name="tipo" value="campo_de_texto">
