
<div class="caja division mt15">
	<label class="mb15 s12">
		<input <?=empty($caja->borde)?'':'checked'?> type="checkbox" name="borde">
		<span><?=t('Borde')?></span>
	</label>
	
	<?php include APP_PATH . "views/ev/fichas/cajas/elementos/margen_sangria.phtml"; ?>

	<div class="mt15 s12">
		<?=t('Imagen de fondo')?>
		<label class="dropimage mb15">
			<input type="file" name="imagenes[]">
			<?php if ($caja->imagenes): ?>
				<img alt="<?=t('Imagen')?>" src="/img/usuarios/<?=$caja->usuarios_idu?>/l.<?=$caja->imagenes?>">
			<?php endif; ?>
		</label>
		<input type="text" name="imagenes_subidas" value="<?=$caja->imagenes?>">
	</div>
</div>
<input type="hidden" name="tipo" value="division">
