
<div class="caja retrato s12 mt15">
	<label class="mb15">
		<input <?=empty($caja->borde)?'':'checked'?> type="checkbox" name="borde">
		<span><?=t('Borde')?></span>
	</label>

	<div>
		<label><?=t('Nombre')?></label>
		<input type="text" name="nombre" value="<?=$caja->nombre?>">
	</div>
	<div>
		<label><?=t('Nombre de la variable')?></label>
		<input type="text" name="variable_nombre" value="<?=$caja->variable_nombre?>">
	</div>
	<small class="s12"><?=t('El nombre de la variable tiene que ser único y estar compuesto solo por letras sin espacios. Se permite la barra baja para separar palabras. En vez de ñ use "ny".')?></small>
</div>
<input type="hidden" name="tipo" value="retrato">
