
<dialog id="dialog-left">
    <header>
        <h6>® ROLEplus.App <sup>4.0</sup></h6>
    </header>
    <hr>
    <section>	
		<a href="/atalaya"><img src="/img/icons/home.svg"> Info</a>

		<a href="/atalaya/acciones"><img src="/img/icons/play.svg"> Acciones</a>

		<a href="/atalaya/archivos"><img src="/img/icons/folder.svg"> Archivos</a>

		<a href="/atalaya/arreglos"><img src="/img/icons/tool.svg"> Arreglos</a>

		<a href="/atalaya/codigos"><img src="/img/icons/gift.svg"> Codigos</a>

		<a href="/atalaya/conversaciones"><img src="/img/icons/message-circle.svg"> Conversaciones</a>

		<a href="/atalaya/logs"><img src="/img/icons/list.svg"> Logs</a>

		<a href="/atalaya/preguntas"><img src="/img/icons/faq.svg"> Preguntas</a>

		<a href="/atalaya/tareas"><img src="/img/icons/trello.svg"> Tareas</a>

		<a href="/atalaya/traducciones"><img src="/img/icons/type.svg"> Traducciones</a>

		<a href="/atalaya/usuarios"><img src="/img/icons/users.svg"> Usuarios</a>
    </section>
</dialog>
<a href="#overlay"></a>
