
<?=$pub->experiencia?> PX

<a data-ajax=".pub-<?=$pub->idu?> .experiencia>div" rel="nofollow" href="/registrados/publicaciones/experiencia/me_encanta/<?=$pub->idu?>" title="<?=t('Me encanta +5 PX.')?>"><img alt="<?=t('Me encanta')?>" height="30" loading="lazy" src="/img/icons/heart<?=($px==5)?'-red':''?>.svg" width="30"></a>

<a data-ajax=".pub-<?=$pub->idu?> .experiencia>div" rel="nofollow" href="/registrados/publicaciones/experiencia/me_gusta/<?=$pub->idu?>" title="<?=t('Me gusta +1 PX.')?>"><img alt="<?=t('Me gusta')?>" height="30" loading="lazy" src="/img/icons/thumbs-up<?=($px==1)?'-yellow':''?>.svg" width="30"></a>
