
<div class="s6">
	<label><?=t('Margen')?></label>
	<input type="text" name="margen" value="<?=$caja->margen?>">
</div>
<div class="s6">
	<label><?=t('Sangría')?></label>
	<input type="text" name="sangria" value="<?=$caja->sangria?>">
</div>
<small class="s12 mb15"><?=t('El formato del margen y de la sangría depende de cuantos parámetros separados por un espacio se añadan. Solo uno afecta a todos los lados. Con dos parámetros, el primero es para arriba y abajo y el segundo para izquierda y derecha. Con tres parámetros, el primero para arriba, el segundo para ziquierda y derecha y el tercero para abajo. Y con cuatro, el primero arriba, el segundo para la derecha, el tercero para abajo y el cuarto para arriba. Por ejemplo, si quiero solo veinte pixeles de margen superior, pondré: 20px 0 0')?></small>
