
<script src="https://accounts.google.com/gsi/client" async></script>

<div id="g_id_onload"
    data-client_id="787739430606-lnei8eglptva554e8a01e66st34cppig.apps.googleusercontent.com"
    data-context="<?=($button==='signup')?'signup':'signin'?>"
    data-ux_mode="popup"
    data-login_uri="<?=DOMAIN . $url ?? ''?>"
    data-auto_prompt="false">
</div>

<?php if ($button === 'signup'): ?>
    <div class="g_id_signin"
        data-type="standard"
        data-shape="rectangular"
        data-theme="outline"
        data-text="signup_with"
        data-size="large"
        data-logo_alignment="left">
    </div>
<?php else: ?>
    <div class="g_id_signin"
        data-type="standard"
        data-shape="rectangular"
        data-theme="outline"
        data-text="signin_with"
        data-size="large"
        data-logo_alignment="left">
    </div>
<?php endif; ?>
