
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
	<input type="hidden" name="cmd" value="_s-xclick" />
	<input type="hidden" name="hosted_button_id" value="<?=$id?>" />
	<input type="hidden" name="currency_code" value="EUR" />
	<button type="submit" <?=$atributos??'class="w100"'?> name="submit" title="PayPal, la forma rápida y segura de pagar en Internet." alt="Suscribirse"><?=$texto?></button>
	<?php /*<input type="image" src="https://www.paypalobjects.com/es_XC/i/btn/btn_subscribe_LG.gif" border="0" name="submit" title="PayPal, la forma rápida y segura de pagar en Internet." alt="Suscribirse" />*/ ?>
</form>

<?php /*<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
	<input type="hidden" name="cmd" value="_s-xclick">
	<input type="hidden" name="hosted_button_id" value="<?=$id?>">
	<input type="hidden" name="currency_code" value="EUR">
	<img alt="" src="https://www.paypalobjects.com/es_ES/i/scr/pixel.gif" style="display:none">
</form>*/ ?>
