<?php
Js::add('theme_picker.min');
?>
<fieldset class="theme-picker">
    <legend><?=t('Caja de selección de tema')?></legend>
	<section>
		<button role="button" data-theme="day" class="transparent"><?=Ku::icon('own/day')?></button>
		<button role="button" data-theme="morning" class="transparent"><?=Ku::icon('own/morning')?></button>
		<button role="button" data-theme="afternoon" class="transparent"><?=Ku::icon('own/afternoon')?></button>
		<button role="button" data-theme="night" class="transparent"><?=Ku::icon('own/night')?></button>
	</section>
</fieldset>
