
<?php if (Session::has('toast')): ?>
	<div class="toast-container">
		<?php foreach (Session::get('toast') as $toast): ?>
			<div class="mb15 toast-<?=$toast_idu=_str::uid()?>">
				<button type="button" class="btn-small" data-remove="parent"><img alt="<?=t('Cerrar caja de información')?>" src="/img/icons/x.svg"></button>
				<h3>INFO</h3>
				<p><?=$toast?></p>
			</div>
			<script>
			setTimeout("$('.toast-<?=$toast_idu?>').fadeOut('slow', function(){ $(this).remove() })", 8000);
			</script>
		<?php endforeach;
		Session::delete('toast'); ?>
	</div>
<?php endif; ?>
