<main sheet>

  <!-- 50% SUPERIOR: IMAGEN DEL EVENTO -->
  <header>
    <img src="/img/aventuras/desapariciones/eventos/jabali.png" alt="Llegada de los cazadores y confiscación de los guardias del Barón">
  </header>

  <!-- SEGUNDA MITAD - 50% SUPERIOR: DISPARADOR DEL EVENTO -->
  <section>
    <h1>Disparador del Evento</h1>
    <p>Se desencadena tras unos minutos de interacción libre en la plaza de Mullensburg.</p>
    <p><i>La tranquilidad y los murmullos de los campesinos se quiebran al escucharse gritos de alborozo desde el linde oeste del asentamiento.</i></p>
    <p><i>«¡Aquí están!», gritan varias voces. Tres cazadores exhaustos entran al pueblo cargando un colosal jabalí en una vara. Pero al comenzar la celebración, irrumpe el batir de armaduras: tres hombres de armas del Barón con sobrevestas negras y amarillas empujan a la multitud. «¡Dispersaos de inmediato!», ruge el líder con la mano en el pomo de su espada. «El jabalí queda requisado para el suministro de la Ciudadela».</i></p>
    <p><i>La tensión estalla. Los campesinos avanzan enfurecidos blandiendo hoces y horcas al grito de: "¡Es nuestra comida! ¡Mi hijo murió de hambre!". Los soldados se ponen en guardia, listos para masacrar a la plebe.</i></p>
    <p>Fuerza a los PJ a definirse. Su reacción ante este abuso marcará cómo los verán tanto los campesinos como la guarnición de la Ciudadela.</p>
  </section>

  <!-- SEGUNDA MITAD - 50% INFERIOR: INFORMACIÓN OCULTA QUE REQUIERE TIRADA -->
  <section>
    <p><b>(Con Negociar a Arduo -30% o Liderazgo a Fácil +20%)</b></p>
    <p>Permite que los jugadores decidan qué bando tomar. Una prueba de Negociar ardua (-30%) aplaca los ánimos y divide la pieza. Si instigan a la multitud, una prueba de Liderazgo fácil (+20%) inicia el combate contra los tres guardias. Si no actúan, alguien lanza una piedra y los soldados derriban a dos lugareños antes de confiscar el jabalí.</p>
  </section>

</main>